/*
 * Generated i18n data for the Ikigai One customer story (/stories/ikigai-one)
 * and the stories index (/stories/). One entry per landing locale; callers fall
 * back to `en` for any locale not present. Regenerate if copy changes.
 */
import en from "./ikigai-one-main.html?raw";
import zh from "./ikigai-one-main.zh.html?raw";
import zhtw from "./ikigai-one-main.zh-tw.html?raw";
import ja from "./ikigai-one-main.ja.html?raw";
import ko from "./ikigai-one-main.ko.html?raw";
import de from "./ikigai-one-main.de.html?raw";
import ru from "./ikigai-one-main.ru.html?raw";
import fr from "./ikigai-one-main.fr.html?raw";
import es from "./ikigai-one-main.es.html?raw";
import ptbr from "./ikigai-one-main.pt-br.html?raw";
import it from "./ikigai-one-main.it.html?raw";
import vi from "./ikigai-one-main.vi.html?raw";
import pl from "./ikigai-one-main.pl.html?raw";
import id from "./ikigai-one-main.id.html?raw";
import nl from "./ikigai-one-main.nl.html?raw";
import ar from "./ikigai-one-main.ar.html?raw";
import tr from "./ikigai-one-main.tr.html?raw";
import uk from "./ikigai-one-main.uk.html?raw";

export const STORY_BODY: Record<string, string> = { en, zh, "zh-tw": zhtw, ja, ko, de, ru, fr, es, "pt-br": ptbr, it, vi, pl, id, nl, ar, tr, uk };

export interface StoryMeta { title: string; description: string }
export const STORY_META: Record<string, StoryMeta> = {
  "en": { title: "“Open Design is our unfair advantage” — Ikigai One", description: "Ikigai One, a US cybersecurity & IT firm, runs its client work on Open Design — brand systems, client deliverables, even a live client portal, all ~50× cheaper than before." },
  "zh": { title: "“Open Design 是我们的不公平优势” — Ikigai One", description: "Ikigai One,一家美国网络安全 & IT 公司,把整条客户交付搬到了 Open Design — 品牌系统、客户物料,甚至一个上线的客户门户,全部比从前便宜约 50 倍。" },
  "zh-tw": { title: "「Open Design 是我們的不公平優勢」 — Ikigai One", description: "Ikigai One 是一家美國的資安與 IT 公司,把整套客戶交付都搬到了 Open Design 上 — 品牌系統、客戶交付物,甚至一個上線的客戶入口網站,全都比從前便宜約 50×。" },
  "ja": { title: "“Open Design は私たちのアンフェアな強みだ” — Ikigai One", description: "米国のサイバーセキュリティ & IT 企業 Ikigai One は、ブランドシステムから納品物、稼働中のクライアントポータルまで、クライアント業務を Open Design で回している — すべて以前より ~50× 安く。" },
  "ko": { title: "“Open Design은 우리의 압도적 우위입니다” — Ikigai One", description: "미국의 사이버보안 & IT 기업 Ikigai One은 클라이언트 업무 전체를 Open Design으로 돌립니다 — 브랜드 시스템, 클라이언트 산출물, 심지어 실제 운영 중인 클라이언트 포털까지, 전부 예전보다 ~50× 저렴하게." },
  "de": { title: "“Open Design ist unser unfairer Vorteil” — Ikigai One", description: "Ikigai One, ein US-amerikanisches Unternehmen für Cybersecurity & IT, wickelt seine Kundenarbeit auf Open Design ab — Markensysteme, Kundendeliverables, sogar ein live geschaltetes Kundenportal, alles ~50× günstiger als zuvor." },
  "ru": { title: "“Open Design — наше несправедливое преимущество” — Ikigai One", description: "Ikigai One, американская компания по кибербезопасности и IT, ведёт всю работу с клиентами в Open Design — брендовые системы, клиентские материалы и даже работающий клиентский портал, и всё это примерно в ~50× дешевле, чем раньше." },
  "fr": { title: "“Open Design, c'est notre avantage déloyal” — Ikigai One", description: "Ikigai One, une entreprise américaine de cybersécurité & d'IT, gère toute sa production client sur Open Design — systèmes de marque, livrables clients, et même un portail client en ligne, le tout ~50× moins cher qu'avant." },
  "es": { title: "“Open Design es nuestra ventaja injusta” — Ikigai One", description: "Ikigai One, una empresa estadounidense de ciberseguridad e IT, gestiona todo su trabajo con clientes en Open Design: sistemas de marca, entregables para clientes e incluso un portal de cliente en producción, todo ~50× más barato que antes." },
  "pt-br": { title: "“O Open Design é a nossa vantagem injusta” — Ikigai One", description: "A Ikigai One, uma empresa norte-americana de cibersegurança e TI, toca todo o trabalho de cliente no Open Design — sistemas de marca, entregáveis para clientes, até um portal de cliente no ar, tudo ~50× mais barato do que antes." },
  "it": { title: "“Open Design è il nostro vantaggio sleale” — Ikigai One", description: "Ikigai One, azienda statunitense di cybersecurity e IT, gestisce il lavoro per i clienti su Open Design — sistemi di brand, deliverable per i clienti, perfino un portale clienti live, il tutto a un costo ~50× inferiore rispetto a prima." },
  "vi": { title: "“Open Design là lợi thế vượt trội của chúng tôi” — Ikigai One", description: "Ikigai One, một công ty an ninh mạng & IT tại Mỹ, vận hành toàn bộ công việc với khách hàng trên Open Design — hệ thống thương hiệu, sản phẩm bàn giao cho khách, thậm chí một cổng thông tin khách hàng chạy thật, tất cả đều rẻ hơn ~50× so với trước." },
  "pl": { title: "“Open Design to nasza nieuczciwa przewaga” — Ikigai One", description: "Ikigai One, amerykańska firma od cyberbezpieczeństwa i IT, realizuje pracę dla klientów na Open Design — systemy marki, materiały dla klientów, a nawet działający portal klienta, wszystko ~50× taniej niż wcześniej." },
  "id": { title: "“Open Design adalah keunggulan tak tertandingi kami” — Ikigai One", description: "Ikigai One, perusahaan keamanan siber & IT asal AS, menjalankan pekerjaan kliennya di Open Design — sistem brand, deliverable klien, bahkan portal klien yang live, semuanya ~50× lebih murah dari sebelumnya." },
  "nl": { title: "“Open Design is ons oneerlijke voordeel” — Ikigai One", description: "Ikigai One, een Amerikaans bedrijf voor cybersecurity & IT, draait zijn klantwerk op Open Design — merksystemen, klantdeliverables, zelfs een live klantenportal, en dat allemaal ~50× goedkoper dan voorheen." },
  "ar": { title: "“Open Design هو ميزتنا التنافسية الحاسمة” — Ikigai One", description: "Ikigai One، شركة أمريكية للأمن السيبراني وتقنية المعلومات، تُدير أعمالها مع العملاء على Open Design — أنظمة العلامة التجارية، ومخرجات العملاء، بل وحتى بوابة عملاء فعلية على الإنترنت، كلّها أرخص بنحو ~50× مما كانت عليه." },
  "tr": { title: "“Open Design haksız rekabet avantajımız” — Ikigai One", description: "ABD merkezli bir siber güvenlik ve BT firması olan Ikigai One, müşteri işlerini Open Design üzerinde yürütüyor — marka sistemleri, müşteri teslimatları, hatta canlı bir müşteri portalı, hepsi eskisinden ~50× daha ucuz." },
  "uk": { title: "“Open Design — це наша нечесна перевага” — Ikigai One", description: "Ikigai One, американська компанія з кібербезпеки та IT, веде роботу з клієнтами на Open Design — бренд-системи, клієнтські матеріали й навіть живий клієнтський портал, і все це ~50× дешевше, ніж раніше." },
};

export interface IndexUi { metaTitle: string; metaDescription: string; eyebrow: string; heading: string; sub: string; readMore: string }
export const INDEX_UI: Record<string, IndexUi> = {
  "en": { metaTitle: "Customer stories — Open Design", metaDescription: "Real studios and teams, real work shipped — straight from the people doing it.", eyebrow: "Customer stories", heading: "Built with Open Design", sub: "Real studios and teams, real work shipped — straight from the people doing it.", readMore: "Read the story →" },
  "zh": { metaTitle: "客户故事 — Open Design", metaDescription: "真实的工作室与团队,真实交付的作品 — 来自亲历者。", eyebrow: "客户故事", heading: "用 Open Design 做出来的", sub: "真实的工作室与团队,真实交付的作品 — 来自亲历者。", readMore: "阅读故事 →" },
  "zh-tw": { metaTitle: "客戶故事 — Open Design", metaDescription: "真實的工作室與團隊,真實交付出去的作品 — 全出自親手做的人。", eyebrow: "客戶故事", heading: "用 Open Design 打造", sub: "真實的工作室與團隊,真實交付出去的作品 — 全出自親手做的人。", readMore: "閱讀故事 →" },
  "ja": { metaTitle: "お客様事例 — Open Design", metaDescription: "実在のスタジオとチーム、実際に世に出た仕事 — 手がけた本人たちの声をそのままに。", eyebrow: "お客様事例", heading: "Open Design で作られた", sub: "実在のスタジオとチーム、実際に世に出た仕事 — 手がけた本人たちの声をそのままに。", readMore: "事例を読む →" },
  "ko": { metaTitle: "고객 사례 — Open Design", metaDescription: "실제 스튜디오와 팀이, 실제로 세상에 내놓은 작업 — 직접 해낸 사람들의 목소리로.", eyebrow: "고객 사례", heading: "Open Design으로 만들다", sub: "실제 스튜디오와 팀이, 실제로 세상에 내놓은 작업 — 직접 해낸 사람들의 목소리로.", readMore: "사례 읽어보기 →" },
  "de": { metaTitle: "Kundenstorys — Open Design", metaDescription: "Echte Studios und Teams, echte ausgelieferte Arbeit — direkt von den Menschen, die sie machen.", eyebrow: "Kundenstorys", heading: "Mit Open Design erstellt", sub: "Echte Studios und Teams, echte ausgelieferte Arbeit — direkt von den Menschen, die sie machen.", readMore: "Story lesen →" },
  "ru": { metaTitle: "Истории клиентов — Open Design", metaDescription: "Настоящие студии и команды, реальная работа в деле — из первых уст от тех, кто её делает.", eyebrow: "Истории клиентов", heading: "Создано в Open Design", sub: "Настоящие студии и команды, реальная работа в деле — из первых уст от тех, кто её делает.", readMore: "Читать историю →" },
  "fr": { metaTitle: "Témoignages clients — Open Design", metaDescription: "De vrais studios et de vraies équipes, du vrai travail livré — directement par celles et ceux qui le font.", eyebrow: "Témoignages clients", heading: "Conçu avec Open Design", sub: "De vrais studios et de vraies équipes, du vrai travail livré — directement par celles et ceux qui le font.", readMore: "Lire le témoignage →" },
  "es": { metaTitle: "Casos de clientes — Open Design", metaDescription: "Estudios y equipos reales, trabajo real publicado: de boca de quienes lo hacen.", eyebrow: "Casos de clientes", heading: "Hecho con Open Design", sub: "Estudios y equipos reales, trabajo real publicado: de boca de quienes lo hacen.", readMore: "Leer el caso →" },
  "pt-br": { metaTitle: "Histórias de clientes — Open Design", metaDescription: "Estúdios e times de verdade, trabalho de verdade entregue — direto de quem põe a mão na massa.", eyebrow: "Histórias de clientes", heading: "Feito com o Open Design", sub: "Estúdios e times de verdade, trabalho de verdade entregue — direto de quem põe a mão na massa.", readMore: "Ler a história →" },
  "it": { metaTitle: "Storie dei clienti — Open Design", metaDescription: "Studi e team reali, lavoro vero portato a termine — direttamente dalle persone che lo fanno.", eyebrow: "Storie dei clienti", heading: "Costruito con Open Design", sub: "Studi e team reali, lavoro vero portato a termine — direttamente dalle persone che lo fanno.", readMore: "Leggi la storia →" },
  "vi": { metaTitle: "Câu chuyện khách hàng — Open Design", metaDescription: "Những studio và đội nhóm thật, những sản phẩm thật đã ra mắt — kể trực tiếp từ chính những người làm ra chúng.", eyebrow: "Câu chuyện khách hàng", heading: "Tạo nên cùng Open Design", sub: "Những studio và đội nhóm thật, những sản phẩm thật đã ra mắt — kể trực tiếp từ chính những người làm ra chúng.", readMore: "Đọc câu chuyện →" },
  "pl": { metaTitle: "Historie klientów — Open Design", metaDescription: "Prawdziwe studia i zespoły, prawdziwa dostarczona praca — prosto od ludzi, którzy ją wykonują.", eyebrow: "Historie klientów", heading: "Zbudowane na Open Design", sub: "Prawdziwe studia i zespoły, prawdziwa dostarczona praca — prosto od ludzi, którzy ją wykonują.", readMore: "Przeczytaj historię →" },
  "id": { metaTitle: "Kisah pelanggan — Open Design", metaDescription: "Studio dan tim nyata, pekerjaan nyata yang berhasil dikirim — langsung dari orang-orang yang mengerjakannya.", eyebrow: "Kisah pelanggan", heading: "Dibangun dengan Open Design", sub: "Studio dan tim nyata, pekerjaan nyata yang berhasil dikirim — langsung dari orang-orang yang mengerjakannya.", readMore: "Baca kisahnya →" },
  "nl": { metaTitle: "Klantverhalen — Open Design", metaDescription: "Echte studio's en teams, echt werk opgeleverd — rechtstreeks van de mensen die het doen.", eyebrow: "Klantverhalen", heading: "Gebouwd met Open Design", sub: "Echte studio's en teams, echt werk opgeleverd — rechtstreeks van de mensen die het doen.", readMore: "Lees het verhaal →" },
  "ar": { metaTitle: "قصص العملاء — Open Design", metaDescription: "استوديوهات وفِرق حقيقية، وأعمال حقيقية أُنجزت — من أصحابها مباشرةً.", eyebrow: "قصص العملاء", heading: "بُني باستخدام Open Design", sub: "استوديوهات وفِرق حقيقية، وأعمال حقيقية أُنجزت — من أصحابها مباشرةً.", readMore: "اقرأ القصة →" },
  "tr": { metaTitle: "Müşteri hikayeleri — Open Design", metaDescription: "Gerçek stüdyolar ve ekipler, gerçekten teslim edilmiş işler — doğrudan işi yapanların ağzından.", eyebrow: "Müşteri hikayeleri", heading: "Open Design ile geliştirildi", sub: "Gerçek stüdyolar ve ekipler, gerçekten teslim edilmiş işler — doğrudan işi yapanların ağzından.", readMore: "Hikayeyi oku →" },
  "uk": { metaTitle: "Історії клієнтів — Open Design", metaDescription: "Справжні студії та команди, справжня випущена робота — напряму від тих, хто її робить.", eyebrow: "Історії клієнтів", heading: "Створено за допомогою Open Design", sub: "Справжні студії та команди, справжня випущена робота — напряму від тих, хто її робить.", readMore: "Читати історію →" },
};

export interface StoryCard { title: string; blurb: string }
export const STORY_CARD: Record<string, StoryCard> = {
  "en": { title: "“Open Design is our unfair advantage”", blurb: "How a US cybersecurity & IT firm runs its client work on Open Design — brand systems, client deliverables, even a live portal, all ~50× cheaper than before." },
  "zh": { title: "“Open Design 是我们的不公平优势”", blurb: "一家美国网络安全 & IT 公司如何用 Open Design 跑通客户交付 — 品牌系统、客户物料,甚至一个上线的门户,全部比从前便宜约 50 倍。" },
  "zh-tw": { title: "「Open Design 是我們的不公平優勢」", blurb: "一家美國資安與 IT 公司如何在 Open Design 上跑完所有客戶交付 — 品牌系統、客戶交付物,甚至一個上線的入口網站,全都比從前便宜約 50×。" },
  "ja": { title: "“Open Design は私たちのアンフェアな強みだ”", blurb: "米国のサイバーセキュリティ & IT 企業が、ブランドシステムから納品物、稼働中のポータルまで、クライアント業務を Open Design で回す方法 — すべて以前より ~50× 安く。" },
  "ko": { title: "“Open Design은 우리의 압도적 우위입니다”", blurb: "미국의 사이버보안 & IT 기업이 클라이언트 업무를 Open Design으로 돌리는 법 — 브랜드 시스템, 클라이언트 산출물, 심지어 실제 운영 중인 포털까지, 전부 예전보다 ~50× 저렴하게." },
  "de": { title: "“Open Design ist unser unfairer Vorteil”", blurb: "Wie ein US-amerikanisches Unternehmen für Cybersecurity & IT seine Kundenarbeit auf Open Design abwickelt — Markensysteme, Kundendeliverables, sogar ein Live-Portal, alles ~50× günstiger als zuvor." },
  "ru": { title: "“Open Design — наше несправедливое преимущество”", blurb: "Как американская компания по кибербезопасности и IT ведёт работу с клиентами в Open Design — брендовые системы, клиентские материалы и даже работающий портал, и всё это примерно в ~50× дешевле, чем раньше." },
  "fr": { title: "“Open Design, c'est notre avantage déloyal”", blurb: "Comment une entreprise américaine de cybersécurité & d'IT gère sa production client sur Open Design — systèmes de marque, livrables clients, et même un portail en ligne, le tout ~50× moins cher qu'avant." },
  "es": { title: "“Open Design es nuestra ventaja injusta”", blurb: "Cómo una empresa estadounidense de ciberseguridad e IT gestiona su trabajo con clientes en Open Design: sistemas de marca, entregables para clientes e incluso un portal en producción, todo ~50× más barato que antes." },
  "pt-br": { title: "“O Open Design é a nossa vantagem injusta”", blurb: "Como uma empresa norte-americana de cibersegurança e TI toca o trabalho de cliente no Open Design — sistemas de marca, entregáveis para clientes, até um portal no ar, tudo ~50× mais barato do que antes." },
  "it": { title: "“Open Design è il nostro vantaggio sleale”", blurb: "Come un'azienda statunitense di cybersecurity e IT gestisce il lavoro per i clienti su Open Design — sistemi di brand, deliverable per i clienti, perfino un portale live, il tutto a un costo ~50× inferiore rispetto a prima." },
  "vi": { title: "“Open Design là lợi thế vượt trội của chúng tôi”", blurb: "Cách một công ty an ninh mạng & IT tại Mỹ vận hành công việc với khách hàng trên Open Design — hệ thống thương hiệu, sản phẩm bàn giao cho khách, thậm chí một cổng thông tin chạy thật, tất cả đều rẻ hơn ~50× so với trước." },
  "pl": { title: "“Open Design to nasza nieuczciwa przewaga”", blurb: "Jak amerykańska firma od cyberbezpieczeństwa i IT realizuje pracę dla klientów na Open Design — systemy marki, materiały dla klientów, a nawet działający portal, wszystko ~50× taniej niż wcześniej." },
  "id": { title: "“Open Design adalah keunggulan tak tertandingi kami”", blurb: "Bagaimana perusahaan keamanan siber & IT asal AS menjalankan pekerjaan kliennya di Open Design — sistem brand, deliverable klien, bahkan portal live, semuanya ~50× lebih murah dari sebelumnya." },
  "nl": { title: "“Open Design is ons oneerlijke voordeel”", blurb: "Hoe een Amerikaans bedrijf voor cybersecurity & IT zijn klantwerk op Open Design draait — merksystemen, klantdeliverables, zelfs een live portal, en dat allemaal ~50× goedkoper dan voorheen." },
  "ar": { title: "“Open Design هو ميزتنا التنافسية الحاسمة”", blurb: "كيف تُدير شركة أمريكية للأمن السيبراني وتقنية المعلومات أعمالها مع العملاء على Open Design — أنظمة العلامة التجارية، ومخرجات العملاء، بل وحتى بوابة فعلية على الإنترنت، كلّها أرخص بنحو ~50× مما كانت عليه." },
  "tr": { title: "“Open Design haksız rekabet avantajımız”", blurb: "ABD merkezli bir siber güvenlik ve BT firması, müşteri işlerini Open Design üzerinde nasıl yürütüyor — marka sistemleri, müşteri teslimatları, hatta canlı bir portal, hepsi eskisinden ~50× daha ucuz." },
  "uk": { title: "“Open Design — це наша нечесна перевага”", blurb: "Як американська компанія з кібербезпеки та IT веде роботу з клієнтами на Open Design — бренд-системи, клієнтські матеріали й навіть живий портал, і все це ~50× дешевше, ніж раніше." },
};

export interface VpItem { h: string; p: string; badge?: string }
export interface StoryVp { heading: string; items: VpItem[]; foot: string }
export const STORY_VP: Record<string, StoryVp> = {
  "en": { heading: "Why teams build with Open Design", items: [{ h: "One design system, every format", p: "Open Design learns your brand and design system, then turns out everything on-brand — decks, reports, graphics, even a live portal — from one place. The more you use it, the more it sounds like your team." }, { h: "Built for teams", p: "A shared cloud workspace — member management, per-seat usage, and per-client separation — so a whole studio or agency runs from one account.", badge: "Coming soon" }, { h: "All-in-one, not three apps", p: "A deep library of polished templates and plugins, with output quality high by default — so you stop juggling separate tools for creative, video, and delivery." }, { h: "Your models, your keys, your pace", p: "Bring your own key, pick any model, and pay by usage — pricing that flexes with uneven workloads." }], foot: "It all adds up to what teams feel first — an order-of-magnitude drop in the time and cost of producing professional design." },
  "zh": { heading: "为什么团队选择 Open Design", items: [{ h: "一套设计系统,产出每一种格式", p: "Open Design 学会你的品牌和设计系统,再把所有东西按品牌产出——提案、报告、图、甚至上线门户,全出自一处。越用越懂你团队的审美。" }, { h: "为团队而生", p: "共享云端工作空间——成员管理、按席位计量、多客户分隔——让整个工作室或 agency 用一个账号协作。", badge: "即将上线" }, { h: "一站式,而不是切三个 app", p: "海量精美模板 + 插件,默认产出质量就很高——不用再在创意、视频、交付之间来回跳工具。" }, { h: "你的模型、你的 key、你的节奏", p: "自带 key、按需选模型、按用量付费——定价随不稳定的工作量灵活伸缩。" }], foot: "这些最终都兑现成团队最先感受到的:把做专业设计的时间和成本,砍下一个数量级。" },
  "zh-tw": { heading: "為什麼團隊都選 Open Design", items: [{ h: "一套設計系統，產出每一種格式", p: "Open Design 學會你的品牌與設計系統，再把所有東西按品牌產出——提案、報告、圖，甚至上線入口，全出自同一處。越用越懂你團隊的調性。" }, { h: "為團隊而生", p: "共享雲端工作空間——成員管理、依席次計量、多客戶分隔——讓整間工作室或 agency 共用一個帳號協作。", badge: "即將上線" }, { h: "一站搞定，而不是切三個 app", p: "海量精緻範本與外掛，產出品質預設就很高——不用再在創意、影片、交付之間來回換工具。" }, { h: "你的模型、你的 key、你的節奏", p: "自帶 key、任選模型、按用量付費——定價隨起伏的工作量靈活伸縮。" }], foot: "這一切最終都兌現成團隊最先感受到的：把產出專業設計的時間與成本，砍掉一個數量級。" },
  "ja": { heading: "チームが Open Design で作る理由", items: [{ h: "ひとつのデザインシステムで、あらゆるフォーマットを", p: "Open Design はあなたのブランドとデザインシステムを学習し、すべてをブランドに沿って生み出します——提案資料、レポート、グラフィック、さらに公開ポータルまで、すべてひとつの場所から。使うほどに、あなたのチームらしさが磨かれていきます。" }, { h: "チームのために設計", p: "共有クラウドワークスペース——メンバー管理、シート単位の利用量、クライアントごとの分離——スタジオや agency 全体をひとつのアカウントで運用できます。", badge: "近日公開" }, { h: "3つのアプリではなく、オールインワン", p: "洗練されたテンプレートとプラグインの豊富なライブラリ。出力品質はデフォルトで高く——クリエイティブ、動画、納品でツールを使い分ける必要はもうありません。" }, { h: "あなたのモデル、あなたの key、あなたのペース", p: "自分の key を持ち込み、好きなモデルを選び、使った分だけ支払う——変動するワークロードに柔軟に対応する料金体系。" }], foot: "それらすべてが、チームが真っ先に実感するものに行き着きます——プロ品質のデザインにかかる時間とコストを、桁違いに削減します。" },
  "ko": { heading: "팀이 Open Design으로 만드는 이유", items: [{ h: "하나의 디자인 시스템, 모든 포맷", p: "Open Design은 당신의 브랜드와 디자인 시스템을 학습한 뒤, 모든 것을 브랜드에 맞게 만들어 냅니다——제안서, 보고서, 그래픽, 라이브 포털까지 한곳에서. 쓰면 쓸수록 당신의 팀다워집니다." }, { h: "팀을 위해 설계", p: "공유 클라우드 워크스페이스——멤버 관리, 시트별 사용량, 클라이언트별 분리——스튜디오나 agency 전체가 하나의 계정으로 움직입니다.", badge: "출시 예정" }, { h: "앱 셋이 아니라, 올인원", p: "정교하게 다듬은 템플릿과 플러그인의 방대한 라이브러리, 결과물 품질은 기본부터 높게——크리에이티브, 영상, 전달까지 따로 도구를 오갈 필요가 없습니다." }, { h: "당신의 모델, 당신의 key, 당신의 속도", p: "직접 key를 가져오고, 원하는 모델을 고르고, 쓴 만큼만 결제——들쭉날쭉한 업무량에 맞춰 유연하게 움직이는 가격." }], foot: "이 모든 것이 결국 팀이 가장 먼저 체감하는 결과로 이어집니다——전문 디자인을 만드는 시간과 비용을 자릿수가 바뀔 만큼 줄여 줍니다." },
  "de": { heading: "Warum Teams mit Open Design arbeiten", items: [{ h: "Ein Designsystem, jedes Format", p: "Open Design lernt Ihre Marke und Ihr Designsystem und produziert dann alles markengerecht – Präsentationen, Reports, Grafiken, sogar ein Live-Portal – aus einer Hand. Je mehr Sie es nutzen, desto stärker klingt es nach Ihrem Team." }, { h: "Für Teams gemacht", p: "Ein gemeinsamer Cloud-Arbeitsbereich – Mitgliederverwaltung, Nutzung pro Sitz und Trennung pro Kunde – damit ein ganzes Studio oder eine agency über ein einziges Konto läuft.", badge: "Demnächst verfügbar" }, { h: "Alles in einem, nicht drei Apps", p: "Eine umfangreiche Bibliothek aus ausgefeilten Vorlagen und Plugins, mit standardmäßig hoher Ausgabequalität – damit Sie nicht länger zwischen separaten Tools für Kreatives, Video und Auslieferung jonglieren." }, { h: "Ihre Modelle, Ihr Key, Ihr Tempo", p: "Bringen Sie Ihren eigenen Key mit, wählen Sie jedes Modell und zahlen Sie nach Nutzung – ein Preismodell, das sich an schwankende Auslastung anpasst." }], foot: "Unterm Strich ergibt das, was Teams als Erstes spüren – eine Reduktion von Zeit und Kosten für professionelles Design um eine Größenordnung." },
  "ru": { heading: "Почему команды создают с Open Design", items: [{ h: "Одна дизайн-система, все форматы", p: "Open Design изучает ваш бренд и дизайн-систему, а затем выпускает всё в едином стиле — презентации, отчёты, графику и даже живой портал — из одного места. Чем больше вы им пользуетесь, тем больше он звучит как ваша команда." }, { h: "Создано для команд", p: "Общее облачное рабочее пространство — управление участниками, учёт по местам и разделение по клиентам — чтобы вся студия или agency работала из одного аккаунта.", badge: "Скоро" }, { h: "Всё в одном, а не три приложения", p: "Богатая библиотека отточенных шаблонов и плагинов с высоким качеством на выходе по умолчанию — чтобы вы перестали жонглировать отдельными инструментами для креатива, видео и сдачи проектов." }, { h: "Ваши модели, ваш key, ваш темп", p: "Подключайте свой key, выбирайте любую модель и платите по факту использования — цена, гибкая под неравномерную нагрузку." }], foot: "Всё это складывается в то, что команды чувствуют первым делом, — сокращение времени и затрат на профессиональный дизайн на порядок." },
  "fr": { heading: "Pourquoi les équipes créent avec Open Design", items: [{ h: "Un système de design, tous les formats", p: "Open Design apprend votre marque et votre système de design, puis produit tout dans votre identité — présentations, rapports, visuels, et même un portail en ligne — depuis un seul endroit. Plus vous l'utilisez, plus il parle comme votre équipe." }, { h: "Conçu pour les équipes", p: "Un espace de travail cloud partagé — gestion des membres, usage par siège et cloisonnement par client — pour qu'un studio ou une agency entière fonctionne depuis un seul compte.", badge: "Bientôt disponible" }, { h: "Tout-en-un, pas trois apps", p: "Une vaste bibliothèque de modèles soignés et de plugins, avec une qualité de rendu élevée par défaut — pour ne plus jongler entre des outils séparés pour le créatif, la vidéo et la livraison." }, { h: "Vos modèles, votre key, votre rythme", p: "Apportez votre key, choisissez n'importe quel modèle et payez à l'usage — une tarification qui s'adapte aux charges de travail irrégulières." }], foot: "Tout cela aboutit à ce que les équipes ressentent en premier : une réduction d'un ordre de grandeur du temps et du coût de production d'un design professionnel." },
  "es": { heading: "Por qué los equipos crean con Open Design", items: [{ h: "Un sistema de diseño, todos los formatos", p: "Open Design aprende tu marca y tu sistema de diseño y luego lo produce todo con tu identidad —presentaciones, informes, gráficos e incluso un portal en vivo— desde un solo lugar. Cuanto más lo usas, más suena como tu equipo." }, { h: "Pensado para equipos", p: "Un espacio de trabajo en la nube compartido —gestión de miembros, uso por asiento y separación por cliente— para que todo un estudio o una agency funcione desde una sola cuenta.", badge: "Próximamente" }, { h: "Todo en uno, no tres apps", p: "Una amplia biblioteca de plantillas y plugins cuidados, con una calidad de salida alta por defecto —para que dejes de hacer malabares con herramientas distintas para creatividad, vídeo y entrega." }, { h: "Tus modelos, tu key, tu ritmo", p: "Trae tu propia key, elige cualquier modelo y paga por uso —precios que se adaptan a cargas de trabajo irregulares." }], foot: "Todo se traduce en lo que los equipos notan primero: una reducción de un orden de magnitud en el tiempo y el coste de producir diseño profesional." },
  "pt-br": { heading: "Por que as equipes criam com o Open Design", items: [{ h: "Um sistema de design, todos os formatos", p: "O Open Design aprende sua marca e seu sistema de design e então entrega tudo dentro da identidade — apresentações, relatórios, peças gráficas e até um portal no ar — de um só lugar. Quanto mais você usa, mais ele soa como o seu time." }, { h: "Feito para equipes", p: "Um espaço de trabalho compartilhado na nuvem — gestão de membros, uso por assento e separação por cliente — para que um estúdio ou uma agency inteira rode em uma única conta.", badge: "Em breve" }, { h: "Tudo em um, não três apps", p: "Uma biblioteca enorme de templates caprichados e plugins, com qualidade de saída alta por padrão — para você parar de alternar entre ferramentas separadas de criação, vídeo e entrega." }, { h: "Seus modelos, sua key, seu ritmo", p: "Traga sua própria key, escolha qualquer modelo e pague por uso — preços que se ajustam a cargas de trabalho irregulares." }], foot: "Tudo isso se traduz no que as equipes sentem primeiro: uma queda de uma ordem de grandeza no tempo e no custo de produzir design profissional." },
  "it": { heading: "Perché i team creano con Open Design", items: [{ h: "Un solo design system, ogni formato", p: "Open Design impara il tuo brand e il tuo design system, poi produce tutto in linea con l'identità — presentazioni, report, grafiche e persino un portale live — da un unico posto. Più lo usi, più suona come il tuo team." }, { h: "Pensato per i team", p: "Uno spazio di lavoro cloud condiviso — gestione dei membri, consumo per postazione e separazione per cliente — così uno studio o una agency intera lavora da un solo account.", badge: "In arrivo" }, { h: "Tutto in uno, non tre app", p: "Una ricca libreria di template curati e plugin, con qualità di output alta per impostazione predefinita — così smetti di destreggiarti tra strumenti separati per creatività, video e consegna." }, { h: "I tuoi modelli, la tua key, il tuo ritmo", p: "Porta la tua key, scegli qualsiasi modello e paga in base all'uso — un prezzo che si adatta a carichi di lavoro variabili." }], foot: "Tutto questo si traduce in ciò che i team percepiscono per primo: un crollo di un ordine di grandezza nei tempi e nei costi per produrre design professionale." },
  "vi": { heading: "Vì sao các nhóm chọn Open Design", items: [{ h: "Một hệ thống thiết kế, mọi định dạng", p: "Open Design học thương hiệu và hệ thống thiết kế của bạn, rồi cho ra mọi thứ đúng nhận diện — bản trình bày, báo cáo, hình ảnh, thậm chí cả một portal trực tuyến — tất cả từ một nơi. Càng dùng, nó càng giống chất riêng của nhóm bạn." }, { h: "Sinh ra cho làm việc nhóm", p: "Một không gian làm việc đám mây dùng chung — quản lý thành viên, tính dung lượng theo chỗ ngồi và tách riêng từng khách hàng — để cả studio hay agency vận hành chỉ với một tài khoản.", badge: "Sắp ra mắt" }, { h: "Tất cả trong một, không phải ba app", p: "Một thư viện đồ sộ gồm template tinh chỉnh và plugin, chất lượng đầu ra cao ngay từ mặc định — để bạn thôi phải nhảy qua lại giữa các công cụ riêng cho sáng tạo, video và bàn giao." }, { h: "Mô hình của bạn, key của bạn, nhịp độ của bạn", p: "Mang key của riêng bạn, chọn bất kỳ mô hình nào và trả theo mức dùng — mức giá co giãn theo khối lượng công việc thất thường." }], foot: "Tất cả cộng lại thành điều các nhóm cảm nhận đầu tiên — thời gian và chi phí làm thiết kế chuyên nghiệp giảm cả một bậc độ lớn." },
  "pl": { heading: "Dlaczego zespoły tworzą z Open Design", items: [{ h: "Jeden system projektowy, każdy format", p: "Open Design uczy się Twojej marki i systemu projektowego, a potem tworzy wszystko zgodnie z identyfikacją — prezentacje, raporty, grafiki, a nawet działający portal — z jednego miejsca. Im częściej go używasz, tym bardziej brzmi jak Twój zespół." }, { h: "Stworzony dla zespołów", p: "Wspólna przestrzeń robocza w chmurze — zarządzanie członkami, zużycie na stanowisko i rozdzielenie na klientów — dzięki czemu całe studio lub agency działa z jednego konta.", badge: "Wkrótce" }, { h: "Wszystko w jednym, a nie trzy aplikacje", p: "Obszerna biblioteka dopracowanych szablonów i wtyczek, z domyślnie wysoką jakością na wyjściu — koniec z żonglowaniem osobnymi narzędziami do kreacji, wideo i dostarczania." }, { h: "Twoje modele, Twój key, Twoje tempo", p: "Podłącz własny key, wybierz dowolny model i płać za użycie — cennik, który dopasowuje się do nierównego obciążenia." }], foot: "Wszystko to składa się na to, co zespoły czują w pierwszej kolejności — spadek czasu i kosztów tworzenia profesjonalnego designu o rząd wielkości." },
  "id": { heading: "Kenapa tim berkarya dengan Open Design", items: [{ h: "Satu design system, semua format", p: "Open Design mempelajari brand dan design system Anda, lalu menghasilkan semuanya sesuai identitas — deck, laporan, grafis, bahkan portal yang tayang langsung — dari satu tempat. Makin sering dipakai, makin terdengar seperti tim Anda." }, { h: "Dirancang untuk tim", p: "Ruang kerja cloud bersama — manajemen anggota, penggunaan per kursi, dan pemisahan per klien — agar satu studio atau agency utuh berjalan dari satu akun.", badge: "Segera hadir" }, { h: "Semua dalam satu, bukan tiga app", p: "Pustaka template dan plugin yang rapi dan melimpah, dengan kualitas output tinggi secara default — supaya Anda berhenti berpindah-pindah alat terpisah untuk kreatif, video, dan pengiriman." }, { h: "Model Anda, key Anda, tempo Anda", p: "Bawa key Anda sendiri, pilih model apa pun, dan bayar sesuai pemakaian — harga yang lentur mengikuti beban kerja yang naik-turun." }], foot: "Semuanya bermuara pada hal yang paling dulu dirasakan tim — waktu dan biaya membuat desain profesional turun satu tingkat besaran." },
  "nl": { heading: "Waarom teams bouwen met Open Design", items: [{ h: "Eén designsysteem, elk formaat", p: "Open Design leert je merk en designsysteem kennen en levert daarna alles on-brand — presentaties, rapporten, graphics, zelfs een live portal — vanuit één plek. Hoe meer je het gebruikt, hoe meer het klinkt als jouw team." }, { h: "Gemaakt voor teams", p: "Een gedeelde cloudwerkruimte — ledenbeheer, gebruik per seat en scheiding per klant — zodat een hele studio of agency vanuit één account werkt.", badge: "Binnenkort" }, { h: "Alles-in-één, geen drie apps", p: "Een uitgebreide bibliotheek met verzorgde templates en plugins, met standaard hoge outputkwaliteit — zodat je niet langer jongleert met losse tools voor creatie, video en oplevering." }, { h: "Jouw modellen, jouw key, jouw tempo", p: "Breng je eigen key mee, kies elk model en betaal naar gebruik — prijzen die meebewegen met wisselende werklast." }], foot: "Het komt allemaal samen in wat teams als eerste voelen — een tienvoudige daling in de tijd en kosten om professioneel design te maken." },
  "ar": { heading: "لماذا تبني الفرق أعمالها مع Open Design", items: [{ h: "نظام تصميم واحد، وكل الصيغ", p: "يتعلّم Open Design علامتك التجارية ونظام التصميم الخاص بك، ثم يُنتج كل شيء متّسقًا مع هويتك — العروض التقديمية والتقارير والرسوميات، وحتى بوابة مباشرة — من مكان واحد. وكلما استخدمته أكثر، صار أقرب إلى نبرة فريقك." }, { h: "مصمَّم للفرق", p: "مساحة عمل سحابية مشتركة — إدارة الأعضاء، واحتساب الاستخدام لكل مقعد، والفصل بين العملاء — لتعمل وكالة أو استوديو بأكمله من حساب واحد.", badge: "قريبًا" }, { h: "كل شيء في مكان واحد، لا ثلاثة تطبيقات", p: "مكتبة عميقة من القوالب المُتقَنة والإضافات، بجودة إخراج عالية افتراضيًا — لتتوقف عن التنقّل بين أدوات منفصلة للإبداع والفيديو والتسليم." }, { h: "نماذجك، ومفتاحك (key)، وإيقاعك", p: "أحضِر مفتاحك (key) الخاص، واختر أي نموذج، وادفع حسب الاستخدام — تسعير يتكيّف مع أحمال العمل المتفاوتة." }], foot: "كل ذلك يتجمّع في ما تشعر به الفرق أولًا — انخفاض بمقدار رتبة كاملة في الوقت والتكلفة اللازمين لإنتاج تصميم احترافي." },
  "tr": { heading: "Ekipler neden Open Design ile üretiyor", items: [{ h: "Tek bir tasarım sistemi, her format", p: "Open Design markanızı ve tasarım sisteminizi öğrenir, ardından her şeyi marka kimliğinize uygun üretir — sunumlar, raporlar, görseller, hatta canlı bir portal — hepsi tek bir yerden. Ne kadar çok kullanırsanız, o kadar ekibinizin sesi gibi olur." }, { h: "Ekipler için tasarlandı", p: "Paylaşımlı bir bulut çalışma alanı — üye yönetimi, koltuk başına kullanım ve müşteri bazında ayrım — böylece bir stüdyonun ya da bir agency'nin tamamı tek bir hesaptan çalışır.", badge: "Çok yakında" }, { h: "Üç ayrı uygulama değil, hepsi bir arada", p: "Özenle hazırlanmış şablon ve eklentilerden oluşan geniş bir kütüphane, varsayılan olarak yüksek çıktı kalitesiyle — böylece kreatif, video ve teslimat için ayrı araçlar arasında gidip gelmeyi bırakırsınız." }, { h: "Modelleriniz, key'iniz, kendi temponuz", p: "Kendi key'inizi getirin, istediğiniz modeli seçin ve kullandığınız kadar ödeyin — dalgalı iş yüküne göre esneyen bir fiyatlandırma." }], foot: "Bütün bunlar, ekiplerin ilk hissettiği şeyde toplanır — profesyonel tasarım üretmenin süresinde ve maliyetinde bir büyüklük mertebesi düşüş." },
  "uk": { heading: "Чому команди створюють з Open Design", items: [{ h: "Одна дизайн-система, усі формати", p: "Open Design вивчає ваш бренд і дизайн-систему, а потім видає все у єдиному стилі — презентації, звіти, графіку й навіть живий портал — з одного місця. Що більше ви ним користуєтесь, то більше він звучить як ваша команда." }, { h: "Створено для команд", p: "Спільний хмарний робочий простір — керування учасниками, облік за місцями та розмежування за клієнтами — щоб уся студія чи agency працювала з одного акаунта.", badge: "Незабаром" }, { h: "Усе в одному, а не три застосунки", p: "Велика бібліотека вивірених шаблонів і плагінів із високою якістю на виході за замовчуванням — щоб ви більше не жонглювали окремими інструментами для креативу, відео та здавання." }, { h: "Ваші моделі, ваш key, ваш темп", p: "Підключайте власний key, обирайте будь-яку модель і платіть за використання — ціна, що гнучко підлаштовується під нерівномірне навантаження." }], foot: "Усе це складається в те, що команди відчувають першим — скорочення часу й витрат на створення професійного дизайну на порядок." },
};
