/*
 * Shared lead-form copy for the Workspace-for-Teams contact-sales surfaces.
 *
 * Extracted from app/pages/enterprise/index.astro so the /enterprise page and
 * the /pricing "Request team access" modal render the exact same form (fields,
 * required rules, options, copy) from one source of truth. The rendering +
 * behavior live in app/_components/enterprise-lead-form.astro; this module is
 * content only. All authored locales below (plus the retired zh-tw) stay in
 * lockstep; anything else falls back to en.
 */

export type SelectOption = { value: string; label: string };

export type EnterpriseLeadCopy = {
  metaTitle: string;
  metaDescription: string;
  h1: string;
  lead: string;
  perks: string[];
  logosTitle: string;
  demosTitle: string;
  demosLead: string;
  incentiveTitle: string;
  incentiveBody: string;
  formHeading: string;
  emailLabel: string;
  emailPlaceholder: string;
  companyLabel: string;
  companyPlaceholder: string;
  teamSizeLabel: string;
  teamSizePlaceholder: string;
  teamSizeOptions: SelectOption[];
  seatsLabel: string;
  seatsPlaceholder: string;
  seatsOptions: SelectOption[];
  countryLabel: string;
  countryPlaceholder: string;
  budgetLabel: string;
  budgetHint: string;
  budgetPlaceholder: string;
  budgetOptions: SelectOption[];
  useCaseLabel: string;
  useCasePlaceholder: string;
  useCaseError: string;
  useCaseOptions: SelectOption[];
  industryLabel: string;
  industryPlaceholder: string;
  industryOptions: SelectOption[];
  roleLabel: string;
  rolePlaceholder: string;
  messageLabel: string;
  messagePlaceholder: string;
  discordLabel: string;
  discordLinkText: string;
  submitLabel: string;
  submittingLabel: string;
  successTitle: string;
  successBody: string;
  errorMessage: string;
  privacyNote: string;
  optional: string;
  requiredError: string;
  emailError: string;
};

const COPY = {
  en: {
    metaTitle: 'Workspace for Teams — Open Design',
    metaDescription:
      'Bring Open Design to your whole team: a shared workspace, shared design systems, and priority onboarding. Tell us what your team needs and we will be in touch.',
    h1: 'Workspace for Teams',
    lead: 'Tell us about your team and what you are trying to build. We are exploring a team edition of Open Design — a shared workspace, shared design systems, and hands-on onboarding — and want to hear from you.',
    perks: [
      'A shared workspace for your whole team',
      'Share design systems, projects, skills, and templates',
      'Centralized billing and organization admin',
    ],
    logosTitle: 'Teams already building with Open Design',
    demosTitle: 'See what teams ship',
    demosLead: 'From a single prompt to a finished artifact — here is the kind of work your team can ship together.',
    incentiveTitle: 'Get early access',
    incentiveBody:
      'Submit this form to claim priority access to the Workspace for Teams beta — plus free testing credits for your team.',
    formHeading: 'Talk to us',
    emailLabel: 'Work email',
    emailPlaceholder: 'you@company.com',
    companyLabel: 'Company',
    companyPlaceholder: 'Company name',
    teamSizeLabel: 'Team size',
    teamSizePlaceholder: 'Select team size',
    teamSizeOptions: [
      { value: '1-10', label: '1–10' },
      { value: '11-50', label: '11–50' },
      { value: '51-200', label: '51–200' },
      { value: '200+', label: '200+' },
    ],
    seatsLabel: 'Expected seats',
    seatsPlaceholder: 'Select a range',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500+' },
    ],
    countryLabel: 'Country / Region',
    countryPlaceholder: 'Select your country or region',
    budgetLabel: 'Monthly budget',
    budgetHint: 'design tools',
    budgetPlaceholder: 'Select a range',
    budgetOptions: [
      { value: 'lt_50', label: 'Under $50 / mo' },
      { value: 'usd_50_200', label: '$50 – $200 / mo' },
      { value: 'usd_200_1k', label: '$200 – $1,000 / mo' },
      { value: 'usd_1k_5k', label: '$1,000 – $5,000 / mo' },
      { value: 'usd_5k_plus', label: '$5,000+ / mo' },
    ],
    useCaseLabel: 'What will you mainly use it for?',
    useCasePlaceholder: 'Select your main use case',
    useCaseError: 'Please select one.',
    useCaseOptions: [
      { value: 'product_design', label: 'Product & app design' },
      { value: 'prototype', label: 'Prototype / app UI' },
      { value: 'design_system', label: 'Design system' },
      { value: 'marketing', label: 'Marketing & landing pages' },
      { value: 'brand', label: 'Brand & visual identity' },
      { value: 'social_media', label: 'Social media & e-commerce creatives' },
      { value: 'poster_print', label: 'Posters & print materials' },
      { value: 'deck', label: 'Presentation / deck' },
      { value: 'video_motion', label: 'Video & motion design' },
      { value: 'illustration', label: 'Illustration & image generation' },
      { value: 'dashboards', label: 'Dashboards / internal tools' },
      { value: 'education', label: 'Education & courseware' },
      { value: 'game_assets', label: 'Game assets' },
      { value: 'other', label: 'Something else' },
    ],
    industryLabel: 'Industry',
    industryPlaceholder: 'Select your industry',
    industryOptions: [
      { value: 'internet_software', label: 'Internet / Software' },
      { value: 'ecommerce_retail', label: 'E-commerce / Retail' },
      { value: 'advertising_marketing', label: 'Advertising / Marketing services' },
      { value: 'finance', label: 'Finance' },
      { value: 'education', label: 'Education & training' },
      { value: 'gaming', label: 'Games' },
      { value: 'media_entertainment', label: 'Media & entertainment' },
      { value: 'manufacturing', label: 'Manufacturing / Hardware' },
      { value: 'healthcare', label: 'Healthcare' },
      { value: 'government_nonprofit', label: 'Government / Nonprofit' },
      { value: 'other', label: 'Other' },
    ],
    roleLabel: 'Role',
    rolePlaceholder: 'Your role',
    messageLabel: 'How can we help?',
    messagePlaceholder: "We're considering Open Design for our team. We'd like to know…",
    discordLabel: 'Join our Discord to talk through Workspace edition perks with the team.',
    discordLinkText: 'Join the chat',
    submitLabel: 'Submit request',
    submittingLabel: 'Submitting…',
    successTitle: 'Thanks — we got it.',
    successBody: "Your request is in. We'll reach out at the email you gave us.",
    errorMessage: 'Something went wrong. Please try again, or email us at support@open-design.ai.',
    privacyNote: 'We only use this to contact you about Open Design for teams. No spam.',
    optional: 'optional',
    requiredError: 'This field is required.',
    emailError: 'Enter a valid work email.',
  },
  zh: {
    metaTitle: 'Workspace 团队版 — Open Design',
    metaDescription:
      '把 Open Design 带给整个团队:共享的工作空间、共享的设计系统,以及优先的上手引导。告诉我们你的团队诉求,我们会尽快联系你。',
    h1: 'Workspace 团队版',
    lead: '告诉我们你的团队,以及你们想做的事。我们正在探索 Open Design 的团队版——共享的工作空间、共享的设计系统、手把手的上手引导——很想听听你的想法。',
    perks: [
      '面向整个团队的共享工作空间',
      '共享设计系统、项目、技能与模板',
      '统一的组织账单与成员管理',
    ],
    logosTitle: '正在使用 Open Design 的团队',
    demosTitle: '看看团队能做出什么',
    demosLead: '从一句话到成品交付物——这些就是你的团队可以一起做出来的东西。',
    incentiveTitle: '抢先体验',
    incentiveBody:
      '提交申请即可优先获得 Workspace 团队版内测资格,以及一份团队专属的免费测试额度。',
    formHeading: '联系我们',
    emailLabel: '工作邮箱',
    emailPlaceholder: 'you@company.com',
    companyLabel: '公司',
    companyPlaceholder: '请输入公司名称',
    teamSizeLabel: '团队规模',
    teamSizePlaceholder: '请选择团队规模',
    teamSizeOptions: [
      { value: '1-10', label: '1–10 人' },
      { value: '11-50', label: '11–50 人' },
      { value: '51-200', label: '51–200 人' },
      { value: '200+', label: '200 人以上' },
    ],
    seatsLabel: '预计需要的席位数',
    seatsPlaceholder: '请选择席位数区间',
    seatsOptions: [
      { value: '1-5', label: '1–5 个' },
      { value: '5-10', label: '5–10 个' },
      { value: '10-20', label: '10–20 个' },
      { value: '20-50', label: '20–50 个' },
      { value: '50-100', label: '50–100 个' },
      { value: '100-200', label: '100–200 个' },
      { value: '200-500', label: '200–500 个' },
      { value: '500+', label: '500 个以上' },
    ],
    countryLabel: '国家 / 地区',
    countryPlaceholder: '请选择国家 / 地区',
    budgetLabel: '每月预算',
    budgetHint: '设计工具投入',
    budgetPlaceholder: '请选择金额区间',
    budgetOptions: [
      { value: 'lt_50', label: '$50 以下 / 月' },
      { value: 'usd_50_200', label: '$50 – $200 / 月' },
      { value: 'usd_200_1k', label: '$200 – $1,000 / 月' },
      { value: 'usd_1k_5k', label: '$1,000 – $5,000 / 月' },
      { value: 'usd_5k_plus', label: '$5,000 以上 / 月' },
    ],
    useCaseLabel: '你们主要用它做什么?',
    useCasePlaceholder: '请选择主要用途',
    useCaseError: '请选择一项。',
    useCaseOptions: [
      { value: 'product_design', label: '产品 / 应用设计' },
      { value: 'prototype', label: '原型 / 应用界面' },
      { value: 'design_system', label: '设计系统' },
      { value: 'marketing', label: '营销 / 落地页' },
      { value: 'brand', label: '品牌视觉 / VI' },
      { value: 'social_media', label: '社媒内容 / 电商素材' },
      { value: 'poster_print', label: '海报 / 印刷物料' },
      { value: 'deck', label: '演示 / Deck' },
      { value: 'video_motion', label: '视频 / 动效' },
      { value: 'illustration', label: '插画 / 图像生成' },
      { value: 'dashboards', label: '仪表盘 / 内部工具' },
      { value: 'education', label: '教学 / 课件' },
      { value: 'game_assets', label: '游戏素材' },
      { value: 'other', label: '其他' },
    ],
    industryLabel: '所属行业',
    industryPlaceholder: '请选择所属行业',
    industryOptions: [
      { value: 'internet_software', label: '互联网 / 软件' },
      { value: 'ecommerce_retail', label: '电商 / 零售' },
      { value: 'advertising_marketing', label: '广告 / 营销服务' },
      { value: 'finance', label: '金融' },
      { value: 'education', label: '教育培训' },
      { value: 'gaming', label: '游戏' },
      { value: 'media_entertainment', label: '文化传媒 / 娱乐' },
      { value: 'manufacturing', label: '制造业 / 硬件' },
      { value: 'healthcare', label: '医疗健康' },
      { value: 'government_nonprofit', label: '政府 / 非营利' },
      { value: 'other', label: '其他' },
    ],
    roleLabel: '职位',
    rolePlaceholder: '请输入您的职位',
    messageLabel: '我们能提供什么帮助?',
    messagePlaceholder: '我正在考虑为团队引入 Open Design,我想了解……',
    discordLabel: '欢迎加入 Discord 群聊,和团队一起讨论 Workspace 版本的权益。',
    discordLinkText: '加入群聊',
    submitLabel: '提交申请',
    submittingLabel: '提交中……',
    successTitle: '收到,谢谢你!',
    successBody: '你的申请已提交,我们会通过你填写的邮箱与你联系。',
    errorMessage: '提交失败,请重试,或发邮件给我们:support@open-design.ai。',
    privacyNote: '我们只会用它就 Open Design 团队版与你联系,不会发垃圾信息。',
    optional: '选填',
    requiredError: '此项必填。',
    emailError: '请输入有效的工作邮箱。',
  },
  'zh-tw': {
    metaTitle: 'Workspace 團隊版 — Open Design',
    metaDescription:
      '把 Open Design 帶給整個團隊:共享的工作空間、共享的設計系統,以及優先的上手引導。告訴我們你的團隊訴求,我們會盡快聯絡你。',
    h1: 'Workspace 團隊版',
    lead: '告訴我們你的團隊,以及你們想做的事。我們正在探索 Open Design 的團隊版——共享的工作空間、共享的設計系統、手把手的上手引導——很想聽聽你的想法。',
    perks: [
      '面向整個團隊的共享工作空間',
      '共享設計系統、專案、技能與範本',
      '統一的組織帳單與成員管理',
    ],
    logosTitle: '正在使用 Open Design 的團隊',
    demosTitle: '看看團隊能做出什麼',
    demosLead: '從一句話到成品交付物——這些就是你的團隊可以一起做出來的東西。',
    incentiveTitle: '搶先體驗',
    incentiveBody:
      '提交申請即可優先取得 Workspace 團隊版內測資格,以及一份團隊專屬的免費測試額度。',
    formHeading: '聯絡我們',
    emailLabel: '工作信箱',
    emailPlaceholder: 'you@company.com',
    companyLabel: '公司',
    companyPlaceholder: '請輸入公司名稱',
    teamSizeLabel: '團隊規模',
    teamSizePlaceholder: '請選擇團隊規模',
    teamSizeOptions: [
      { value: '1-10', label: '1–10 人' },
      { value: '11-50', label: '11–50 人' },
      { value: '51-200', label: '51–200 人' },
      { value: '200+', label: '200 人以上' },
    ],
    seatsLabel: '預計需要的席位數',
    seatsPlaceholder: '請選擇席位數區間',
    seatsOptions: [
      { value: '1-5', label: '1–5 個' },
      { value: '5-10', label: '5–10 個' },
      { value: '10-20', label: '10–20 個' },
      { value: '20-50', label: '20–50 個' },
      { value: '50-100', label: '50–100 個' },
      { value: '100-200', label: '100–200 個' },
      { value: '200-500', label: '200–500 個' },
      { value: '500+', label: '500 個以上' },
    ],
    countryLabel: '國家 / 地區',
    countryPlaceholder: '請選擇國家 / 地區',
    budgetLabel: '每月預算',
    budgetHint: '設計工具投入',
    budgetPlaceholder: '請選擇金額區間',
    budgetOptions: [
      { value: 'lt_50', label: '$50 以下 / 月' },
      { value: 'usd_50_200', label: '$50 – $200 / 月' },
      { value: 'usd_200_1k', label: '$200 – $1,000 / 月' },
      { value: 'usd_1k_5k', label: '$1,000 – $5,000 / 月' },
      { value: 'usd_5k_plus', label: '$5,000 以上 / 月' },
    ],
    useCaseLabel: '你們主要用它做什麼?',
    useCasePlaceholder: '請選擇主要用途',
    useCaseError: '請選擇一項。',
    useCaseOptions: [
      { value: 'product_design', label: '產品 / 應用設計' },
      { value: 'prototype', label: '原型 / 應用介面' },
      { value: 'design_system', label: '設計系統' },
      { value: 'marketing', label: '行銷 / 落地頁' },
      { value: 'brand', label: '品牌視覺 / VI' },
      { value: 'social_media', label: '社群內容 / 電商素材' },
      { value: 'poster_print', label: '海報 / 印刷物料' },
      { value: 'deck', label: '簡報 / Deck' },
      { value: 'video_motion', label: '影片 / 動效' },
      { value: 'illustration', label: '插畫 / 圖像生成' },
      { value: 'dashboards', label: '儀表板 / 內部工具' },
      { value: 'education', label: '教學 / 課件' },
      { value: 'game_assets', label: '遊戲素材' },
      { value: 'other', label: '其他' },
    ],
    industryLabel: '所屬行業',
    industryPlaceholder: '請選擇所屬行業',
    industryOptions: [
      { value: 'internet_software', label: '網際網路 / 軟體' },
      { value: 'ecommerce_retail', label: '電商 / 零售' },
      { value: 'advertising_marketing', label: '廣告 / 行銷服務' },
      { value: 'finance', label: '金融' },
      { value: 'education', label: '教育培訓' },
      { value: 'gaming', label: '遊戲' },
      { value: 'media_entertainment', label: '文化傳媒 / 娛樂' },
      { value: 'manufacturing', label: '製造業 / 硬體' },
      { value: 'healthcare', label: '醫療健康' },
      { value: 'government_nonprofit', label: '政府 / 非營利' },
      { value: 'other', label: '其他' },
    ],
    roleLabel: '職位',
    rolePlaceholder: '請輸入您的職位',
    messageLabel: '我們能提供什麼幫助?',
    messagePlaceholder: '我正在考慮為團隊引入 Open Design,我想了解……',
    discordLabel: '歡迎加入 Discord 群聊,和團隊一起討論 Workspace 版本的權益。',
    discordLinkText: '加入群聊',
    submitLabel: '提交申請',
    submittingLabel: '提交中……',
    successTitle: '收到,謝謝你!',
    successBody: '你的申請已提交,我們會透過你填寫的信箱與你聯絡。',
    errorMessage: '提交失敗,請重試,或寄信給我們:support@open-design.ai。',
    privacyNote: '我們只會用它就 Open Design 團隊版與你聯絡,不會發垃圾訊息。',
    optional: '選填',
    requiredError: '此項必填。',
    emailError: '請輸入有效的工作信箱。',
  },
  ja: {
    metaTitle: 'チーム向けワークスペース — Open Design',
    metaDescription:
      'チーム全体で Open Design を:共有ワークスペース、共有デザインシステム、優先オンボーディング。チームのニーズをお聞かせください。追ってご連絡します。',
    h1: 'チーム向けワークスペース',
    lead: 'あなたのチームと、作りたいものについて教えてください。私たちは Open Design のチーム版——共有ワークスペース、共有デザインシステム、手厚いオンボーディング——を検討しており、皆さんの声をぜひ聞かせていただきたいと思っています。',
    perks: [
      'チーム全体で使える共有ワークスペース',
      'デザインシステム・プロジェクト・スキル・テンプレートを共有',
      '一元化された請求と組織管理',
    ],
    logosTitle: 'Open Design で制作しているチーム',
    demosTitle: 'チームの成果物を見る',
    demosLead: 'ひとつのプロンプトから完成品まで——チームで一緒に作れるものをご紹介します。',
    incentiveTitle: '先行アクセス',
    incentiveBody:
      'フォームを送信すると、チーム向けワークスペースのベータ版への優先アクセスと、チーム用の無料テストクレジットを獲得できます。',
    formHeading: 'お問い合わせ',
    emailLabel: '仕事用メールアドレス',
    emailPlaceholder: 'you@company.com',
    companyLabel: '会社名',
    companyPlaceholder: '会社名を入力',
    teamSizeLabel: 'チーム規模',
    teamSizePlaceholder: 'チーム規模を選択',
    teamSizeOptions: [
      { value: '1-10', label: '1–10 名' },
      { value: '11-50', label: '11–50 名' },
      { value: '51-200', label: '51–200 名' },
      { value: '200+', label: '200 名以上' },
    ],
    seatsLabel: '必要なシート数(見込み)',
    seatsPlaceholder: '範囲を選択',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500 以上' },
    ],
    countryLabel: '国 / 地域',
    countryPlaceholder: '国 / 地域を選択',
    budgetLabel: '月間予算',
    budgetHint: 'デザインツール支出',
    budgetPlaceholder: '金額帯を選択',
    budgetOptions: [
      { value: 'lt_50', label: '月 $50 未満' },
      { value: 'usd_50_200', label: '月 $50 – $200' },
      { value: 'usd_200_1k', label: '月 $200 – $1,000' },
      { value: 'usd_1k_5k', label: '月 $1,000 – $5,000' },
      { value: 'usd_5k_plus', label: '月 $5,000 以上' },
    ],
    useCaseLabel: '主な用途は何ですか?',
    useCasePlaceholder: '主な用途を選択',
    useCaseError: '1 つ選択してください。',
    useCaseOptions: [
      { value: 'product_design', label: 'プロダクト / アプリデザイン' },
      { value: 'prototype', label: 'プロトタイプ / アプリ UI' },
      { value: 'design_system', label: 'デザインシステム' },
      { value: 'marketing', label: 'マーケティング / LP' },
      { value: 'brand', label: 'ブランド / VI' },
      { value: 'social_media', label: 'SNS / EC 素材' },
      { value: 'poster_print', label: 'ポスター / 印刷物' },
      { value: 'deck', label: 'プレゼン資料 / Deck' },
      { value: 'video_motion', label: '動画 / モーション' },
      { value: 'illustration', label: 'イラスト / 画像生成' },
      { value: 'dashboards', label: 'ダッシュボード / 社内ツール' },
      { value: 'education', label: '教育 / 教材' },
      { value: 'game_assets', label: 'ゲームアセット' },
      { value: 'other', label: 'その他' },
    ],
    industryLabel: '業界',
    industryPlaceholder: '業界を選択',
    industryOptions: [
      { value: 'internet_software', label: 'インターネット / ソフトウェア' },
      { value: 'ecommerce_retail', label: 'EC / 小売' },
      { value: 'advertising_marketing', label: '広告 / マーケティング' },
      { value: 'finance', label: '金融' },
      { value: 'education', label: '教育' },
      { value: 'gaming', label: 'ゲーム' },
      { value: 'media_entertainment', label: 'メディア / エンタメ' },
      { value: 'manufacturing', label: '製造 / ハードウェア' },
      { value: 'healthcare', label: '医療・ヘルスケア' },
      { value: 'government_nonprofit', label: '行政 / 非営利' },
      { value: 'other', label: 'その他' },
    ],
    roleLabel: '役職',
    rolePlaceholder: '役職を入力',
    messageLabel: 'どんなサポートが必要ですか?',
    messagePlaceholder: 'チームでの Open Design 導入を検討しています。知りたいのは……',
    discordLabel: 'Discord に参加して、チーム版の特典についてぜひ話しましょう。',
    discordLinkText: '参加する',
    submitLabel: '送信',
    submittingLabel: '送信中……',
    successTitle: 'ありがとうございます!',
    successBody: 'リクエストを受け付けました。ご記入いただいたメールアドレスにご連絡します。',
    errorMessage: '送信に失敗しました。再試行するか、support@open-design.ai までメールでご連絡ください。',
    privacyNote: 'ご記入内容はチーム版のご案内のみに使用します。スパムは送りません。',
    optional: '任意',
    requiredError: 'この項目は必須です。',
    emailError: '有効な仕事用メールアドレスを入力してください。',
  },
  ko: {
    metaTitle: '팀을 위한 워크스페이스 — Open Design',
    metaDescription:
      '팀 전체와 함께 Open Design을: 공유 워크스페이스, 공유 디자인 시스템, 우선 온보딩. 팀에 필요한 것을 알려주시면 곧 연락드리겠습니다.',
    h1: '팀을 위한 워크스페이스',
    lead: '팀과 만들고 싶은 것에 대해 알려주세요. 저희는 Open Design 팀 에디션——공유 워크스페이스, 공유 디자인 시스템, 밀착 온보딩——을 준비하고 있으며 여러분의 의견을 듣고 싶습니다.',
    perks: [
      '팀 전체를 위한 공유 워크스페이스',
      '디자인 시스템·프로젝트·스킬·템플릿 공유',
      '통합 결제 및 조직 관리',
    ],
    logosTitle: 'Open Design으로 만들고 있는 팀들',
    demosTitle: '팀이 만들어내는 결과물',
    demosLead: '프롬프트 한 줄에서 완성된 결과물까지——팀이 함께 만들 수 있는 작업들입니다.',
    incentiveTitle: '얼리 액세스',
    incentiveBody:
      '이 폼을 제출하면 팀 워크스페이스 베타 우선 액세스와 팀 전용 무료 테스트 크레딧을 받을 수 있습니다.',
    formHeading: '문의하기',
    emailLabel: '업무용 이메일',
    emailPlaceholder: 'you@company.com',
    companyLabel: '회사',
    companyPlaceholder: '회사명 입력',
    teamSizeLabel: '팀 규모',
    teamSizePlaceholder: '팀 규모 선택',
    teamSizeOptions: [
      { value: '1-10', label: '1–10명' },
      { value: '11-50', label: '11–50명' },
      { value: '51-200', label: '51–200명' },
      { value: '200+', label: '200명 이상' },
    ],
    seatsLabel: '예상 시트 수',
    seatsPlaceholder: '범위 선택',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500 이상' },
    ],
    countryLabel: '국가 / 지역',
    countryPlaceholder: '국가 / 지역 선택',
    budgetLabel: '월 예산',
    budgetHint: '디자인 툴 지출',
    budgetPlaceholder: '금액대 선택',
    budgetOptions: [
      { value: 'lt_50', label: '월 $50 미만' },
      { value: 'usd_50_200', label: '월 $50 – $200' },
      { value: 'usd_200_1k', label: '월 $200 – $1,000' },
      { value: 'usd_1k_5k', label: '월 $1,000 – $5,000' },
      { value: 'usd_5k_plus', label: '월 $5,000 이상' },
    ],
    useCaseLabel: '주로 어디에 사용하시나요?',
    useCasePlaceholder: '주요 용도 선택',
    useCaseError: '하나를 선택해 주세요.',
    useCaseOptions: [
      { value: 'product_design', label: '제품 / 앱 디자인' },
      { value: 'prototype', label: '프로토타입 / 앱 UI' },
      { value: 'design_system', label: '디자인 시스템' },
      { value: 'marketing', label: '마케팅 / 랜딩 페이지' },
      { value: 'brand', label: '브랜드 / VI' },
      { value: 'social_media', label: '소셜 미디어 / 커머스 소재' },
      { value: 'poster_print', label: '포스터 / 인쇄물' },
      { value: 'deck', label: '프레젠테이션 / 덱' },
      { value: 'video_motion', label: '영상 / 모션' },
      { value: 'illustration', label: '일러스트 / 이미지 생성' },
      { value: 'dashboards', label: '대시보드 / 사내 도구' },
      { value: 'education', label: '교육 / 강의 자료' },
      { value: 'game_assets', label: '게임 에셋' },
      { value: 'other', label: '기타' },
    ],
    industryLabel: '업종',
    industryPlaceholder: '업종 선택',
    industryOptions: [
      { value: 'internet_software', label: '인터넷 / 소프트웨어' },
      { value: 'ecommerce_retail', label: '이커머스 / 리테일' },
      { value: 'advertising_marketing', label: '광고 / 마케팅' },
      { value: 'finance', label: '금융' },
      { value: 'education', label: '교육' },
      { value: 'gaming', label: '게임' },
      { value: 'media_entertainment', label: '미디어 / 엔터테인먼트' },
      { value: 'manufacturing', label: '제조 / 하드웨어' },
      { value: 'healthcare', label: '헬스케어' },
      { value: 'government_nonprofit', label: '정부 / 비영리' },
      { value: 'other', label: '기타' },
    ],
    roleLabel: '직함',
    rolePlaceholder: '직함 입력',
    messageLabel: '어떤 도움이 필요하신가요?',
    messagePlaceholder: '팀에 Open Design 도입을 검토 중입니다. 알고 싶은 것은……',
    discordLabel: 'Discord에 참여해 팀 에디션 혜택에 대해 함께 이야기해요.',
    discordLinkText: '참여하기',
    submitLabel: '요청 보내기',
    submittingLabel: '보내는 중……',
    successTitle: '감사합니다!',
    successBody: '요청이 접수되었습니다. 입력하신 이메일로 연락드리겠습니다.',
    errorMessage: '문제가 발생했습니다. 다시 시도하거나 support@open-design.ai로 메일 주세요.',
    privacyNote: '입력하신 정보는 팀 에디션 안내에만 사용됩니다. 스팸은 없습니다.',
    optional: '선택',
    requiredError: '필수 항목입니다.',
    emailError: '유효한 업무용 이메일을 입력해 주세요.',
  },
  de: {
    metaTitle: 'Workspace für Teams — Open Design',
    metaDescription:
      'Open Design fürs ganze Team: gemeinsamer Workspace, geteilte Designsysteme und Priority-Onboarding. Sag uns, was dein Team braucht — wir melden uns.',
    h1: 'Workspace für Teams',
    lead: 'Erzähl uns von deinem Team und dem, was ihr bauen wollt. Wir arbeiten an einer Team-Edition von Open Design — gemeinsamer Workspace, geteilte Designsysteme, persönliches Onboarding — und wollen von euch hören.',
    perks: [
      'Ein gemeinsamer Workspace für das ganze Team',
      'Designsysteme, Projekte, Skills und Vorlagen teilen',
      'Zentrale Abrechnung und Organisationsverwaltung',
    ],
    logosTitle: 'Teams, die bereits mit Open Design bauen',
    demosTitle: 'Was Teams liefern',
    demosLead: 'Vom einzelnen Prompt zum fertigen Artefakt — solche Arbeiten kann dein Team gemeinsam liefern.',
    incentiveTitle: 'Early Access sichern',
    incentiveBody:
      'Schick das Formular ab und erhalte bevorzugten Zugang zur Workspace-für-Teams-Beta — plus kostenlose Test-Credits für dein Team.',
    formHeading: 'Sprich mit uns',
    emailLabel: 'Geschäftliche E-Mail',
    emailPlaceholder: 'you@company.com',
    companyLabel: 'Unternehmen',
    companyPlaceholder: 'Firmenname',
    teamSizeLabel: 'Teamgröße',
    teamSizePlaceholder: 'Teamgröße wählen',
    teamSizeOptions: [
      { value: '1-10', label: '1–10' },
      { value: '11-50', label: '11–50' },
      { value: '51-200', label: '51–200' },
      { value: '200+', label: '200+' },
    ],
    seatsLabel: 'Voraussichtliche Seats',
    seatsPlaceholder: 'Bereich wählen',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500+' },
    ],
    countryLabel: 'Land / Region',
    countryPlaceholder: 'Land / Region wählen',
    budgetLabel: 'Monatsbudget',
    budgetHint: 'Design-Tools',
    budgetPlaceholder: 'Bereich wählen',
    budgetOptions: [
      { value: 'lt_50', label: 'Unter $50 / Monat' },
      { value: 'usd_50_200', label: '$50 – $200 / Monat' },
      { value: 'usd_200_1k', label: '$200 – $1,000 / Monat' },
      { value: 'usd_1k_5k', label: '$1,000 – $5,000 / Monat' },
      { value: 'usd_5k_plus', label: '$5,000+ / Monat' },
    ],
    useCaseLabel: 'Wofür nutzt ihr es?',
    useCasePlaceholder: 'Hauptanwendungsfall wählen',
    useCaseError: 'Bitte wähle eine Option.',
    useCaseOptions: [
      { value: 'product_design', label: 'Produkt- & App-Design' },
      { value: 'prototype', label: 'Prototyp / App-UI' },
      { value: 'design_system', label: 'Designsystem' },
      { value: 'marketing', label: 'Marketing & Landingpages' },
      { value: 'brand', label: 'Marke & Visual Identity' },
      { value: 'social_media', label: 'Social-Media- & E-Commerce-Assets' },
      { value: 'poster_print', label: 'Poster & Printmaterial' },
      { value: 'deck', label: 'Präsentation / Deck' },
      { value: 'video_motion', label: 'Video & Motion Design' },
      { value: 'illustration', label: 'Illustration & Bildgenerierung' },
      { value: 'dashboards', label: 'Dashboards / interne Tools' },
      { value: 'education', label: 'Bildung & Kursmaterial' },
      { value: 'game_assets', label: 'Game-Assets' },
      { value: 'other', label: 'Etwas anderes' },
    ],
    industryLabel: 'Branche',
    industryPlaceholder: 'Branche wählen',
    industryOptions: [
      { value: 'internet_software', label: 'Internet / Software' },
      { value: 'ecommerce_retail', label: 'E-Commerce / Handel' },
      { value: 'advertising_marketing', label: 'Werbung / Marketing' },
      { value: 'finance', label: 'Finanzen' },
      { value: 'education', label: 'Bildung' },
      { value: 'gaming', label: 'Games' },
      { value: 'media_entertainment', label: 'Medien & Entertainment' },
      { value: 'manufacturing', label: 'Fertigung / Hardware' },
      { value: 'healthcare', label: 'Gesundheitswesen' },
      { value: 'government_nonprofit', label: 'Öffentlicher Sektor / Non-Profit' },
      { value: 'other', label: 'Andere Branche' },
    ],
    roleLabel: 'Rolle',
    rolePlaceholder: 'Deine Rolle',
    messageLabel: 'Wie können wir helfen?',
    messagePlaceholder: 'Wir erwägen Open Design für unser Team. Wir würden gern wissen …',
    discordLabel: 'Tritt unserem Discord bei und sprich mit dem Team über die Vorteile der Workspace-Edition.',
    discordLinkText: 'Zum Chat',
    submitLabel: 'Anfrage senden',
    submittingLabel: 'Wird gesendet …',
    successTitle: 'Danke — angekommen!',
    successBody: 'Deine Anfrage ist eingegangen. Wir melden uns unter der angegebenen E-Mail-Adresse.',
    errorMessage: 'Etwas ist schiefgelaufen. Bitte versuch es erneut oder schreib uns an support@open-design.ai.',
    privacyNote: 'Wir nutzen deine Angaben nur, um dich zu Open Design für Teams zu kontaktieren. Kein Spam.',
    optional: 'optional',
    requiredError: 'Pflichtfeld.',
    emailError: 'Gib eine gültige geschäftliche E-Mail-Adresse ein.',
  },
  fr: {
    metaTitle: 'Workspace pour les équipes — Open Design',
    metaDescription:
      "Apportez Open Design à toute votre équipe : un espace de travail partagé, des design systems partagés et un onboarding prioritaire. Dites-nous ce dont votre équipe a besoin, nous vous recontacterons.",
    h1: 'Workspace pour les équipes',
    lead: "Parlez-nous de votre équipe et de ce que vous voulez construire. Nous préparons une édition équipe d'Open Design — espace de travail partagé, design systems partagés, onboarding accompagné — et nous voulons vous entendre.",
    perks: [
      "Un espace de travail partagé pour toute l'équipe",
      'Partagez design systems, projets, skills et templates',
      "Facturation centralisée et administration de l'organisation",
    ],
    logosTitle: 'Des équipes construisent déjà avec Open Design',
    demosTitle: 'Ce que les équipes livrent',
    demosLead: "D'un simple prompt à un livrable fini — voici le genre de travail que votre équipe peut produire ensemble.",
    incentiveTitle: 'Accès anticipé',
    incentiveBody:
      'Envoyez ce formulaire pour obtenir un accès prioritaire à la bêta Workspace pour les équipes — plus des crédits de test gratuits pour votre équipe.',
    formHeading: 'Parlons-en',
    emailLabel: 'E-mail professionnel',
    emailPlaceholder: 'you@company.com',
    companyLabel: 'Entreprise',
    companyPlaceholder: "Nom de l'entreprise",
    teamSizeLabel: "Taille de l'équipe",
    teamSizePlaceholder: 'Sélectionnez la taille',
    teamSizeOptions: [
      { value: '1-10', label: '1–10' },
      { value: '11-50', label: '11–50' },
      { value: '51-200', label: '51–200' },
      { value: '200+', label: '200+' },
    ],
    seatsLabel: 'Nombre de sièges estimé',
    seatsPlaceholder: 'Sélectionnez une fourchette',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500+' },
    ],
    countryLabel: 'Pays / Région',
    countryPlaceholder: 'Sélectionnez votre pays ou région',
    budgetLabel: 'Budget mensuel',
    budgetHint: 'outils de design',
    budgetPlaceholder: 'Sélectionnez une fourchette',
    budgetOptions: [
      { value: 'lt_50', label: 'Moins de 50 $ / mois' },
      { value: 'usd_50_200', label: '50 $ – 200 $ / mois' },
      { value: 'usd_200_1k', label: '200 $ – 1 000 $ / mois' },
      { value: 'usd_1k_5k', label: '1 000 $ – 5 000 $ / mois' },
      { value: 'usd_5k_plus', label: '5 000 $ et plus / mois' },
    ],
    useCaseLabel: 'Usage principal',
    useCasePlaceholder: "Sélectionnez l'usage principal",
    useCaseError: 'Veuillez en sélectionner un.',
    useCaseOptions: [
      { value: 'product_design', label: 'Design produit & app' },
      { value: 'prototype', label: "Prototype / UI d'app" },
      { value: 'design_system', label: 'Design system' },
      { value: 'marketing', label: 'Marketing & landing pages' },
      { value: 'brand', label: 'Marque & identité visuelle' },
      { value: 'social_media', label: 'Réseaux sociaux & e-commerce' },
      { value: 'poster_print', label: 'Affiches & print' },
      { value: 'deck', label: 'Présentation / deck' },
      { value: 'video_motion', label: 'Vidéo & motion design' },
      { value: 'illustration', label: "Illustration & génération d'images" },
      { value: 'dashboards', label: 'Dashboards / outils internes' },
      { value: 'education', label: 'Éducation & supports de cours' },
      { value: 'game_assets', label: 'Assets de jeu' },
      { value: 'other', label: 'Autre chose' },
    ],
    industryLabel: 'Secteur d\'activité',
    industryPlaceholder: 'Sélectionnez votre secteur',
    industryOptions: [
      { value: 'internet_software', label: 'Internet / Logiciels' },
      { value: 'ecommerce_retail', label: 'E-commerce / Retail' },
      { value: 'advertising_marketing', label: 'Publicité / Marketing' },
      { value: 'finance', label: 'Finance' },
      { value: 'education', label: 'Éducation' },
      { value: 'gaming', label: 'Jeux vidéo' },
      { value: 'media_entertainment', label: 'Médias & divertissement' },
      { value: 'manufacturing', label: 'Industrie / Hardware' },
      { value: 'healthcare', label: 'Santé' },
      { value: 'government_nonprofit', label: 'Secteur public / ONG' },
      { value: 'other', label: 'Autre' },
    ],
    roleLabel: 'Rôle',
    rolePlaceholder: 'Votre rôle',
    messageLabel: 'Comment pouvons-nous aider ?',
    messagePlaceholder: "Nous envisageons Open Design pour notre équipe. Nous aimerions savoir…",
    discordLabel: "Rejoignez notre Discord pour discuter des avantages de l'édition Workspace avec l'équipe.",
    discordLinkText: 'Rejoindre',
    submitLabel: 'Envoyer la demande',
    submittingLabel: 'Envoi…',
    successTitle: 'Merci, bien reçu !',
    successBody: "Votre demande est enregistrée. Nous vous contacterons à l'adresse indiquée.",
    errorMessage: "Une erreur s'est produite. Réessayez ou écrivez-nous à support@open-design.ai.",
    privacyNote: "Nous n'utilisons ces informations que pour vous contacter au sujet d'Open Design pour les équipes. Pas de spam.",
    optional: 'facultatif',
    requiredError: 'Ce champ est obligatoire.',
    emailError: 'Saisissez un e-mail professionnel valide.',
  },
  ru: {
    metaTitle: 'Workspace для команд — Open Design',
    metaDescription:
      'Open Design для всей команды: общее рабочее пространство, общие дизайн-системы и приоритетный онбординг. Расскажите, что нужно вашей команде, — мы свяжемся с вами.',
    h1: 'Workspace для команд',
    lead: 'Расскажите о своей команде и о том, что вы хотите создавать. Мы готовим командную версию Open Design — общее рабочее пространство, общие дизайн-системы, персональный онбординг — и хотим услышать вас.',
    perks: [
      'Общее рабочее пространство для всей команды',
      'Общие дизайн-системы, проекты, скиллы и шаблоны',
      'Единый биллинг и управление организацией',
    ],
    logosTitle: 'Команды уже работают в Open Design',
    demosTitle: 'Что создают команды',
    demosLead: 'От одного промпта до готового результата — вот что ваша команда может делать вместе.',
    incentiveTitle: 'Ранний доступ',
    incentiveBody:
      'Отправьте форму, чтобы получить приоритетный доступ к бете Workspace для команд и бесплатные тестовые кредиты для вашей команды.',
    formHeading: 'Свяжитесь с нами',
    emailLabel: 'Рабочая почта',
    emailPlaceholder: 'you@company.com',
    companyLabel: 'Компания',
    companyPlaceholder: 'Название компании',
    teamSizeLabel: 'Размер команды',
    teamSizePlaceholder: 'Выберите размер',
    teamSizeOptions: [
      { value: '1-10', label: '1–10' },
      { value: '11-50', label: '11–50' },
      { value: '51-200', label: '51–200' },
      { value: '200+', label: '200+' },
    ],
    seatsLabel: 'Ожидаемое число мест',
    seatsPlaceholder: 'Выберите диапазон',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500+' },
    ],
    countryLabel: 'Страна / регион',
    countryPlaceholder: 'Выберите страну или регион',
    budgetLabel: 'Месячный бюджет',
    budgetHint: '',
    budgetPlaceholder: 'Выберите диапазон',
    budgetOptions: [
      { value: 'lt_50', label: 'До $50 / мес' },
      { value: 'usd_50_200', label: '$50 – $200 / мес' },
      { value: 'usd_200_1k', label: '$200 – $1,000 / мес' },
      { value: 'usd_1k_5k', label: '$1,000 – $5,000 / мес' },
      { value: 'usd_5k_plus', label: 'От $5,000 / мес' },
    ],
    useCaseLabel: 'Для чего вы будете его использовать?',
    useCasePlaceholder: 'Выберите основной сценарий',
    useCaseError: 'Выберите один вариант.',
    useCaseOptions: [
      { value: 'product_design', label: 'Продуктовый / app-дизайн' },
      { value: 'prototype', label: 'Прототип / интерфейс приложения' },
      { value: 'design_system', label: 'Дизайн-система' },
      { value: 'marketing', label: 'Маркетинг / лендинги' },
      { value: 'brand', label: 'Бренд / фирменный стиль' },
      { value: 'social_media', label: 'Соцсети / e-commerce' },
      { value: 'poster_print', label: 'Постеры / полиграфия' },
      { value: 'deck', label: 'Презентации / деки' },
      { value: 'video_motion', label: 'Видео / моушн' },
      { value: 'illustration', label: 'Иллюстрации / генерация изображений' },
      { value: 'dashboards', label: 'Дашборды / внутренние инструменты' },
      { value: 'education', label: 'Обучение / учебные материалы' },
      { value: 'game_assets', label: 'Игровые ассеты' },
      { value: 'other', label: 'Другое' },
    ],
    industryLabel: 'Отрасль',
    industryPlaceholder: 'Выберите отрасль',
    industryOptions: [
      { value: 'internet_software', label: 'Интернет / ПО' },
      { value: 'ecommerce_retail', label: 'E-commerce / ритейл' },
      { value: 'advertising_marketing', label: 'Реклама / маркетинг' },
      { value: 'finance', label: 'Финансы' },
      { value: 'education', label: 'Образование' },
      { value: 'gaming', label: 'Игры' },
      { value: 'media_entertainment', label: 'Медиа и развлечения' },
      { value: 'manufacturing', label: 'Производство / hardware' },
      { value: 'healthcare', label: 'Здравоохранение' },
      { value: 'government_nonprofit', label: 'Госсектор / НКО' },
      { value: 'other', label: 'Другое' },
    ],
    roleLabel: 'Должность',
    rolePlaceholder: 'Ваша должность',
    messageLabel: 'Чем мы можем помочь?',
    messagePlaceholder: 'Мы рассматриваем Open Design для нашей команды. Хотели бы узнать…',
    discordLabel: 'Заходите в наш Discord, чтобы обсудить преимущества командной версии с командой.',
    discordLinkText: 'Присоединиться',
    submitLabel: 'Отправить заявку',
    submittingLabel: 'Отправка…',
    successTitle: 'Спасибо, получили!',
    successBody: 'Ваша заявка принята. Мы напишем на указанную почту.',
    errorMessage: 'Что-то пошло не так. Попробуйте ещё раз или напишите нам: support@open-design.ai.',
    privacyNote: 'Мы используем эти данные только для связи по поводу Open Design для команд. Никакого спама.',
    optional: 'необязательно',
    requiredError: 'Обязательное поле.',
    emailError: 'Введите корректную рабочую почту.',
  },
  es: {
    metaTitle: 'Workspace para equipos — Open Design',
    metaDescription:
      'Lleva Open Design a todo tu equipo: un espacio de trabajo compartido, design systems compartidos y onboarding prioritario. Cuéntanos qué necesita tu equipo y te contactaremos.',
    h1: 'Workspace para equipos',
    lead: 'Cuéntanos sobre tu equipo y lo que queréis construir. Estamos explorando una edición para equipos de Open Design — espacio de trabajo compartido, design systems compartidos y onboarding cercano — y queremos escucharte.',
    perks: [
      'Un espacio de trabajo compartido para todo el equipo',
      'Comparte design systems, proyectos, skills y plantillas',
      'Facturación centralizada y administración de la organización',
    ],
    logosTitle: 'Equipos que ya construyen con Open Design',
    demosTitle: 'Lo que los equipos entregan',
    demosLead: 'De un solo prompt a un artefacto terminado: este es el tipo de trabajo que tu equipo puede entregar junto.',
    incentiveTitle: 'Consigue acceso anticipado',
    incentiveBody:
      'Envía este formulario para obtener acceso prioritario a la beta de Workspace para equipos, además de créditos de prueba gratis para tu equipo.',
    formHeading: 'Habla con nosotros',
    emailLabel: 'Email de trabajo',
    emailPlaceholder: 'you@company.com',
    companyLabel: 'Empresa',
    companyPlaceholder: 'Nombre de la empresa',
    teamSizeLabel: 'Tamaño del equipo',
    teamSizePlaceholder: 'Selecciona el tamaño',
    teamSizeOptions: [
      { value: '1-10', label: '1–10' },
      { value: '11-50', label: '11–50' },
      { value: '51-200', label: '51–200' },
      { value: '200+', label: '200+' },
    ],
    seatsLabel: 'Puestos estimados',
    seatsPlaceholder: 'Selecciona un rango',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500+' },
    ],
    countryLabel: 'País / Región',
    countryPlaceholder: 'Selecciona tu país o región',
    budgetLabel: 'Presupuesto mensual',
    budgetHint: '',
    budgetPlaceholder: 'Selecciona un rango',
    budgetOptions: [
      { value: 'lt_50', label: 'Menos de $50 / mes' },
      { value: 'usd_50_200', label: '$50 – $200 / mes' },
      { value: 'usd_200_1k', label: '$200 – $1,000 / mes' },
      { value: 'usd_1k_5k', label: '$1,000 – $5,000 / mes' },
      { value: 'usd_5k_plus', label: 'Más de $5,000 / mes' },
    ],
    useCaseLabel: '¿Para qué lo usaréis principalmente?',
    useCasePlaceholder: 'Selecciona el uso principal',
    useCaseError: 'Selecciona una opción.',
    useCaseOptions: [
      { value: 'product_design', label: 'Diseño de producto y apps' },
      { value: 'prototype', label: 'Prototipo / UI de app' },
      { value: 'design_system', label: 'Design system' },
      { value: 'marketing', label: 'Marketing y landing pages' },
      { value: 'brand', label: 'Marca e identidad visual' },
      { value: 'social_media', label: 'Redes sociales y e-commerce' },
      { value: 'poster_print', label: 'Pósters e impresión' },
      { value: 'deck', label: 'Presentaciones / decks' },
      { value: 'video_motion', label: 'Vídeo y motion' },
      { value: 'illustration', label: 'Ilustración y generación de imágenes' },
      { value: 'dashboards', label: 'Dashboards / herramientas internas' },
      { value: 'education', label: 'Educación y material formativo' },
      { value: 'game_assets', label: 'Assets de juegos' },
      { value: 'other', label: 'Otra cosa' },
    ],
    industryLabel: 'Sector',
    industryPlaceholder: 'Selecciona tu sector',
    industryOptions: [
      { value: 'internet_software', label: 'Internet / Software' },
      { value: 'ecommerce_retail', label: 'E-commerce / Retail' },
      { value: 'advertising_marketing', label: 'Publicidad / Marketing' },
      { value: 'finance', label: 'Finanzas' },
      { value: 'education', label: 'Educación' },
      { value: 'gaming', label: 'Videojuegos' },
      { value: 'media_entertainment', label: 'Medios y entretenimiento' },
      { value: 'manufacturing', label: 'Industria / Hardware' },
      { value: 'healthcare', label: 'Salud' },
      { value: 'government_nonprofit', label: 'Sector público / ONG' },
      { value: 'other', label: 'Otro' },
    ],
    roleLabel: 'Rol',
    rolePlaceholder: 'Tu rol',
    messageLabel: '¿Cómo podemos ayudar?',
    messagePlaceholder: 'Estamos considerando Open Design para nuestro equipo. Nos gustaría saber…',
    discordLabel: 'Únete a nuestro Discord para hablar con el equipo sobre las ventajas de la edición Workspace.',
    discordLinkText: 'Unirse',
    submitLabel: 'Enviar solicitud',
    submittingLabel: 'Enviando…',
    successTitle: '¡Gracias, recibido!',
    successBody: 'Tu solicitud está registrada. Te contactaremos al email que nos diste.',
    errorMessage: 'Algo salió mal. Inténtalo de nuevo o escríbenos a support@open-design.ai.',
    privacyNote: 'Solo usaremos estos datos para contactarte sobre Open Design para equipos. Sin spam.',
    optional: 'opcional',
    requiredError: 'Este campo es obligatorio.',
    emailError: 'Introduce un email de trabajo válido.',
  },
  'pt-br': {
    metaTitle: 'Workspace para times — Open Design',
    metaDescription:
      'Leve o Open Design para todo o seu time: workspace compartilhado, design systems compartilhados e onboarding prioritário. Conte o que seu time precisa e entraremos em contato.',
    h1: 'Workspace para times',
    lead: 'Conte sobre seu time e o que vocês querem construir. Estamos explorando uma edição para times do Open Design — workspace compartilhado, design systems compartilhados e onboarding próximo — e queremos ouvir você.',
    perks: [
      'Um workspace compartilhado para todo o time',
      'Compartilhe design systems, projetos, skills e templates',
      'Cobrança centralizada e administração da organização',
    ],
    logosTitle: 'Times que já constroem com o Open Design',
    demosTitle: 'O que os times entregam',
    demosLead: 'De um único prompt a um artefato pronto — este é o tipo de trabalho que seu time pode entregar junto.',
    incentiveTitle: 'Garanta acesso antecipado',
    incentiveBody:
      'Envie este formulário para ter acesso prioritário à beta do Workspace para times — além de créditos de teste grátis para o seu time.',
    formHeading: 'Fale com a gente',
    emailLabel: 'E-mail de trabalho',
    emailPlaceholder: 'you@company.com',
    companyLabel: 'Empresa',
    companyPlaceholder: 'Nome da empresa',
    teamSizeLabel: 'Tamanho do time',
    teamSizePlaceholder: 'Selecione o tamanho',
    teamSizeOptions: [
      { value: '1-10', label: '1–10' },
      { value: '11-50', label: '11–50' },
      { value: '51-200', label: '51–200' },
      { value: '200+', label: '200+' },
    ],
    seatsLabel: 'Assentos estimados',
    seatsPlaceholder: 'Selecione uma faixa',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500+' },
    ],
    countryLabel: 'País / Região',
    countryPlaceholder: 'Selecione seu país ou região',
    budgetLabel: 'Orçamento mensal',
    budgetHint: '',
    budgetPlaceholder: 'Selecione uma faixa',
    budgetOptions: [
      { value: 'lt_50', label: 'Menos de $50 / mês' },
      { value: 'usd_50_200', label: '$50 – $200 / mês' },
      { value: 'usd_200_1k', label: '$200 – $1,000 / mês' },
      { value: 'usd_1k_5k', label: '$1,000 – $5,000 / mês' },
      { value: 'usd_5k_plus', label: 'Acima de $5,000 / mês' },
    ],
    useCaseLabel: 'Uso principal',
    useCasePlaceholder: 'Selecione o uso principal',
    useCaseError: 'Selecione uma opção.',
    useCaseOptions: [
      { value: 'product_design', label: 'Design de produto e apps' },
      { value: 'prototype', label: 'Protótipo / UI de app' },
      { value: 'design_system', label: 'Design system' },
      { value: 'marketing', label: 'Marketing e landing pages' },
      { value: 'brand', label: 'Marca e identidade visual' },
      { value: 'social_media', label: 'Redes sociais e e-commerce' },
      { value: 'poster_print', label: 'Pôsteres e impressos' },
      { value: 'deck', label: 'Apresentações / decks' },
      { value: 'video_motion', label: 'Vídeo e motion' },
      { value: 'illustration', label: 'Ilustração e geração de imagens' },
      { value: 'dashboards', label: 'Dashboards / ferramentas internas' },
      { value: 'education', label: 'Educação e material didático' },
      { value: 'game_assets', label: 'Assets de jogos' },
      { value: 'other', label: 'Outra coisa' },
    ],
    industryLabel: 'Setor',
    industryPlaceholder: 'Selecione seu setor',
    industryOptions: [
      { value: 'internet_software', label: 'Internet / Software' },
      { value: 'ecommerce_retail', label: 'E-commerce / Varejo' },
      { value: 'advertising_marketing', label: 'Publicidade / Marketing' },
      { value: 'finance', label: 'Finanças' },
      { value: 'education', label: 'Educação' },
      { value: 'gaming', label: 'Games' },
      { value: 'media_entertainment', label: 'Mídia e entretenimento' },
      { value: 'manufacturing', label: 'Indústria / Hardware' },
      { value: 'healthcare', label: 'Saúde' },
      { value: 'government_nonprofit', label: 'Setor público / ONG' },
      { value: 'other', label: 'Outro' },
    ],
    roleLabel: 'Cargo',
    rolePlaceholder: 'Seu cargo',
    messageLabel: 'Como podemos ajudar?',
    messagePlaceholder: 'Estamos considerando o Open Design para nosso time. Gostaríamos de saber…',
    discordLabel: 'Entre no nosso Discord para conversar com o time sobre as vantagens da edição Workspace.',
    discordLinkText: 'Entrar',
    submitLabel: 'Enviar solicitação',
    submittingLabel: 'Enviando…',
    successTitle: 'Obrigado — recebido!',
    successBody: 'Sua solicitação foi registrada. Entraremos em contato pelo e-mail informado.',
    errorMessage: 'Algo deu errado. Tente de novo ou escreva para support@open-design.ai.',
    privacyNote: 'Usamos esses dados apenas para falar com você sobre o Open Design para times. Sem spam.',
    optional: 'opcional',
    requiredError: 'Campo obrigatório.',
    emailError: 'Informe um e-mail de trabalho válido.',
  },
  it: {
    metaTitle: 'Workspace per team — Open Design',
    metaDescription:
      'Porta Open Design a tutto il tuo team: workspace condiviso, design system condivisi e onboarding prioritario. Dicci di cosa ha bisogno il tuo team e ti contatteremo.',
    h1: 'Workspace per team',
    lead: 'Raccontaci del tuo team e di cosa volete costruire. Stiamo esplorando una edizione team di Open Design — workspace condiviso, design system condivisi, onboarding dedicato — e vogliamo sentire la tua opinione.',
    perks: [
      'Un workspace condiviso per tutto il team',
      'Condividi design system, progetti, skill e template',
      "Fatturazione centralizzata e amministrazione dell'organizzazione",
    ],
    logosTitle: 'Team che già costruiscono con Open Design',
    demosTitle: 'Cosa consegnano i team',
    demosLead: 'Da un singolo prompt a un artefatto finito: ecco il tipo di lavoro che il tuo team può realizzare insieme.',
    incentiveTitle: 'Accesso anticipato',
    incentiveBody:
      'Invia questo modulo per ottenere accesso prioritario alla beta di Workspace per team, più crediti di prova gratuiti per il tuo team.',
    formHeading: 'Parla con noi',
    emailLabel: 'Email di lavoro',
    emailPlaceholder: 'you@company.com',
    companyLabel: 'Azienda',
    companyPlaceholder: "Nome dell'azienda",
    teamSizeLabel: 'Dimensione del team',
    teamSizePlaceholder: 'Seleziona la dimensione',
    teamSizeOptions: [
      { value: '1-10', label: '1–10' },
      { value: '11-50', label: '11–50' },
      { value: '51-200', label: '51–200' },
      { value: '200+', label: '200+' },
    ],
    seatsLabel: 'Postazioni previste',
    seatsPlaceholder: 'Seleziona un intervallo',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500+' },
    ],
    countryLabel: 'Paese / Regione',
    countryPlaceholder: 'Seleziona il tuo paese o regione',
    budgetLabel: 'Budget mensile',
    budgetHint: '',
    budgetPlaceholder: 'Seleziona un intervallo',
    budgetOptions: [
      { value: 'lt_50', label: 'Meno di $50 / mese' },
      { value: 'usd_50_200', label: '$50 – $200 / mese' },
      { value: 'usd_200_1k', label: '$200 – $1,000 / mese' },
      { value: 'usd_1k_5k', label: '$1,000 – $5,000 / mese' },
      { value: 'usd_5k_plus', label: 'Oltre $5,000 / mese' },
    ],
    useCaseLabel: 'Uso principale',
    useCasePlaceholder: "Seleziona l'uso principale",
    useCaseError: 'Seleziona una voce.',
    useCaseOptions: [
      { value: 'product_design', label: 'Design di prodotto e app' },
      { value: 'prototype', label: 'Prototipo / UI di app' },
      { value: 'design_system', label: 'Design system' },
      { value: 'marketing', label: 'Marketing e landing page' },
      { value: 'brand', label: 'Brand e identità visiva' },
      { value: 'social_media', label: 'Social media ed e-commerce' },
      { value: 'poster_print', label: 'Poster e materiale stampato' },
      { value: 'deck', label: 'Presentazioni / deck' },
      { value: 'video_motion', label: 'Video e motion' },
      { value: 'illustration', label: 'Illustrazione e generazione immagini' },
      { value: 'dashboards', label: 'Dashboard / strumenti interni' },
      { value: 'education', label: 'Formazione e materiale didattico' },
      { value: 'game_assets', label: 'Asset di gioco' },
      { value: 'other', label: 'Altro' },
    ],
    industryLabel: 'Settore',
    industryPlaceholder: 'Seleziona il tuo settore',
    industryOptions: [
      { value: 'internet_software', label: 'Internet / Software' },
      { value: 'ecommerce_retail', label: 'E-commerce / Retail' },
      { value: 'advertising_marketing', label: 'Pubblicità / Marketing' },
      { value: 'finance', label: 'Finanza' },
      { value: 'education', label: 'Istruzione' },
      { value: 'gaming', label: 'Videogiochi' },
      { value: 'media_entertainment', label: 'Media e intrattenimento' },
      { value: 'manufacturing', label: 'Manifattura / Hardware' },
      { value: 'healthcare', label: 'Sanità' },
      { value: 'government_nonprofit', label: 'Settore pubblico / Non profit' },
      { value: 'other', label: 'Altro' },
    ],
    roleLabel: 'Ruolo',
    rolePlaceholder: 'Il tuo ruolo',
    messageLabel: 'Come possiamo aiutarti?',
    messagePlaceholder: 'Stiamo valutando Open Design per il nostro team. Vorremmo sapere…',
    discordLabel: "Unisciti al nostro Discord per parlare con il team dei vantaggi dell'edizione Workspace.",
    discordLinkText: 'Unisciti',
    submitLabel: 'Invia richiesta',
    submittingLabel: 'Invio…',
    successTitle: 'Grazie, ricevuto!',
    successBody: "La tua richiesta è registrata. Ti contatteremo all'email indicata.",
    errorMessage: 'Qualcosa è andato storto. Riprova o scrivici a support@open-design.ai.',
    privacyNote: 'Useremo questi dati solo per contattarti su Open Design per team. Niente spam.',
    optional: 'facoltativo',
    requiredError: 'Campo obbligatorio.',
    emailError: "Inserisci un'email di lavoro valida.",
  },
  tr: {
    metaTitle: 'Takımlar için Workspace — Open Design',
    metaDescription:
      "Open Design'ı tüm takımınıza getirin: ortak çalışma alanı, ortak tasarım sistemleri ve öncelikli onboarding. Takımınızın ihtiyacını anlatın, size ulaşalım.",
    h1: 'Takımlar için Workspace',
    lead: "Bize takımınızı ve ne inşa etmek istediğinizi anlatın. Open Design'ın takım sürümü üzerinde çalışıyoruz — ortak çalışma alanı, ortak tasarım sistemleri, birebir onboarding — ve sizi dinlemek istiyoruz.",
    perks: [
      'Tüm takım için ortak bir çalışma alanı',
      "Tasarım sistemlerini, projeleri, skill'leri ve şablonları paylaşın",
      'Merkezi faturalama ve organizasyon yönetimi',
    ],
    logosTitle: 'Open Design ile üreten takımlar',
    demosTitle: 'Takımlar neler üretiyor',
    demosLead: "Tek bir prompt'tan bitmiş bir işe — takımınızın birlikte üretebileceği işler burada.",
    incentiveTitle: 'Erken erişim kazanın',
    incentiveBody:
      'Bu formu gönderin, Takımlar için Workspace betasına öncelikli erişim ve takımınıza özel ücretsiz test kredileri kazanın.',
    formHeading: 'Bizimle konuşun',
    emailLabel: 'İş e-postası',
    emailPlaceholder: 'you@company.com',
    companyLabel: 'Şirket',
    companyPlaceholder: 'Şirket adı',
    teamSizeLabel: 'Takım büyüklüğü',
    teamSizePlaceholder: 'Takım büyüklüğü seçin',
    teamSizeOptions: [
      { value: '1-10', label: '1–10' },
      { value: '11-50', label: '11–50' },
      { value: '51-200', label: '51–200' },
      { value: '200+', label: '200+' },
    ],
    seatsLabel: 'Tahmini koltuk sayısı',
    seatsPlaceholder: 'Aralık seçin',
    seatsOptions: [
      { value: '1-5', label: '1–5' },
      { value: '5-10', label: '5–10' },
      { value: '10-20', label: '10–20' },
      { value: '20-50', label: '20–50' },
      { value: '50-100', label: '50–100' },
      { value: '100-200', label: '100–200' },
      { value: '200-500', label: '200–500' },
      { value: '500+', label: '500+' },
    ],
    countryLabel: 'Ülke / Bölge',
    countryPlaceholder: 'Ülke veya bölge seçin',
    budgetLabel: 'Aylık bütçe',
    budgetHint: 'tasarım araçları',
    budgetPlaceholder: 'Aralık seçin',
    budgetOptions: [
      { value: 'lt_50', label: 'Ayda $50 altı' },
      { value: 'usd_50_200', label: 'Ayda $50 – $200' },
      { value: 'usd_200_1k', label: 'Ayda $200 – $1,000' },
      { value: 'usd_1k_5k', label: 'Ayda $1,000 – $5,000' },
      { value: 'usd_5k_plus', label: 'Ayda $5,000 üzeri' },
    ],
    useCaseLabel: 'Onu en çok ne için kullanacaksınız?',
    useCasePlaceholder: 'Ana kullanım senaryosunu seçin',
    useCaseError: 'Lütfen bir seçenek seçin.',
    useCaseOptions: [
      { value: 'product_design', label: 'Ürün ve uygulama tasarımı' },
      { value: 'prototype', label: 'Prototip / uygulama arayüzü' },
      { value: 'design_system', label: 'Tasarım sistemi' },
      { value: 'marketing', label: 'Pazarlama ve landing page' },
      { value: 'brand', label: 'Marka ve görsel kimlik' },
      { value: 'social_media', label: 'Sosyal medya ve e-ticaret görselleri' },
      { value: 'poster_print', label: 'Poster ve baskı materyalleri' },
      { value: 'deck', label: 'Sunum / deck' },
      { value: 'video_motion', label: 'Video ve motion' },
      { value: 'illustration', label: 'İllüstrasyon ve görsel üretimi' },
      { value: 'dashboards', label: 'Dashboard / iç araçlar' },
      { value: 'education', label: 'Eğitim ve ders materyali' },
      { value: 'game_assets', label: "Oyun asset'leri" },
      { value: 'other', label: 'Başka bir şey' },
    ],
    industryLabel: 'Sektör',
    industryPlaceholder: 'Sektör seçin',
    industryOptions: [
      { value: 'internet_software', label: 'İnternet / Yazılım' },
      { value: 'ecommerce_retail', label: 'E-ticaret / Perakende' },
      { value: 'advertising_marketing', label: 'Reklam / Pazarlama' },
      { value: 'finance', label: 'Finans' },
      { value: 'education', label: 'Eğitim' },
      { value: 'gaming', label: 'Oyun' },
      { value: 'media_entertainment', label: 'Medya ve eğlence' },
      { value: 'manufacturing', label: 'Üretim / Donanım' },
      { value: 'healthcare', label: 'Sağlık' },
      { value: 'government_nonprofit', label: 'Kamu / Kâr amacı gütmeyen' },
      { value: 'other', label: 'Diğer' },
    ],
    roleLabel: 'Rol',
    rolePlaceholder: 'Rolünüz',
    messageLabel: 'Nasıl yardımcı olabiliriz?',
    messagePlaceholder: "Takımımız için Open Design'ı değerlendiriyoruz. Şunu öğrenmek isteriz…",
    discordLabel: "Discord'umuza katılın, Workspace sürümünün avantajlarını ekiple konuşun.",
    discordLinkText: 'Sohbete katıl',
    submitLabel: 'Talep gönder',
    submittingLabel: 'Gönderiliyor…',
    successTitle: 'Teşekkürler, aldık!',
    successBody: 'Talebiniz alındı. Verdiğiniz e-posta üzerinden size ulaşacağız.',
    errorMessage: 'Bir şeyler ters gitti. Lütfen tekrar deneyin ya da support@open-design.ai adresine yazın.',
    privacyNote: 'Bu bilgileri yalnızca takımlar için Open Design hakkında sizinle iletişim kurmak için kullanırız. Spam yok.',
    optional: 'isteğe bağlı',
    requiredError: 'Bu alan zorunludur.',
    emailError: 'Geçerli bir iş e-postası girin.',
  },
} satisfies Record<string, EnterpriseLeadCopy>;

export function getEnterpriseLeadCopy(locale: string): EnterpriseLeadCopy {
  return COPY[locale as keyof typeof COPY] ?? COPY.en;
}

// Country / Region dropdown — ISO 3166-1 alpha-2 codes (uninhabited /
// technical territories dropped), localized at build time via
// Intl.DisplayNames and sorted with the page locale's collator, so the zh
// pages list 中文国名 by pinyin and en lists English names alphabetically.
// The inline script preselects the visitor's region inferred from the
// browser locale (zh-CN → CN, bare "ja" maximizes to JP).
export const REGION_CODES = [
  'AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ',
  'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR',
  'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN',
  'CO', 'CR', 'CU', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE',
  'EG', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF',
  'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GT', 'GU', 'GW', 'GY', 'HK', 'HN',
  'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM', 'JO',
  'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC',
  'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH',
  'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY',
  'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA',
  'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO',
  'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SK', 'SL', 'SM', 'SN',
  'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TG', 'TH', 'TJ', 'TK', 'TL',
  'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VA', 'VC',
  'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW',
];

/**
 * Country / Region options localized at build time via Intl.DisplayNames and
 * sorted with the page locale's collator, so the zh pages list 中文国名 by
 * pinyin and en lists English names alphabetically.
 */
export function buildCountryOptions(locale: string): SelectOption[] {
  const regionNames = new Intl.DisplayNames([locale, 'en'], { type: 'region' });
  const regionCollator = new Intl.Collator(locale);
  return REGION_CODES.map((code) => ({
    value: code,
    label: regionNames.of(code) ?? code,
  }))
    .filter((opt) => opt.label !== opt.value)
    .sort((a, b) => regionCollator.compare(a.label, b.label));
}
