apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-design.fullname" . }}
type: Opaque
data:
  {{- if .Values.config.apiToken }}
  OD_API_TOKEN: {{ .Values.config.apiToken | b64enc | quote }}
  {{- else }}
  {{- fail "CRITICAL ERROR: config.apiToken cannot be empty." }}
  {{- end }}